// web/src/app/features/sono/components/awakenings-clock.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import {
  SLEEP_AXIS_ORIGIN_H,
  awakeDensityOpacity,
  axisRange,
  buildAwakeClock,
  peakAwakeWindow,
  toTimingBar,
  type SleepPeriod,
} from '@vitale/shared';

interface BinVM { x: number; w: number; opacity: number; }
interface TickVM { x: number; label: string; }

const W = 640;
const H = 64;
const PAD_BOTTOM = 16;

/**
 * O relógio de vigília: os despertares de todas as noites da janela sobrepostos
 * num eixo de hora do dia, por densidade. Responde "eu acordo sempre às 3h?".
 *
 * Três estados, e a tela diz qual é: a fonte não reporta, reporta e não houve,
 * reporta e houve. Sem score, sem índice — o dado do usuário mostra vigília × nota
 * correndo ao contrário do que um score assumiria (spec §6).
 */
@Component({
  selector: 'rt-awakenings-clock',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @switch (clock().coverage) {
      @case ('unreported') {
        <p class="note">Seu relógio não reporta despertares — não dá para saber.</p>
      }
      @case ('none') {
        <p class="note">Nenhum despertar registrado nas últimas {{ clock().nightsReporting }} noites.</p>
      }
      @default {
        <svg [attr.viewBox]="'0 0 ' + w + ' ' + h" class="chart" role="img"
          aria-label="Densidade de despertares por hora da noite">
          @for (b of bins(); track b.x) {
            <rect class="bin" [attr.x]="b.x" y="0" [attr.width]="b.w" [attr.height]="innerH" [attr.opacity]="b.opacity" />
          }
          <line class="base" x1="0" [attr.x2]="w" [attr.y1]="innerH" [attr.y2]="innerH" />
          @for (t of ticks(); track t.label) {
            <text class="axis mono" [attr.x]="t.x" [attr.y]="h - 3" text-anchor="middle">{{ t.label }}</text>
          }
        </svg>
        <p class="note">{{ peakText() }}</p>
      }
    }
  `,
  styles: [`
    :host { display: block; }
    .chart { width: 100%; height: auto; display: block; }
    /* Vigília é amarelo, em toda tela de sono; a opacidade faz o "quanto". */
    .bin { fill: var(--sleep-awake); }
    .base { stroke: var(--line); stroke-width: 1; }
    .axis { font-size: 9.5px; fill: var(--ink-4); }
    .note { margin: 6px 0 0; font-size: 12.5px; line-height: 1.5; color: var(--ink-3); }
  `],
})
export class AwakeningsClockComponent {
  readonly periods = input.required<SleepPeriod[]>();

  protected readonly w = W;
  protected readonly h = H;
  protected readonly innerH = H - PAD_BOTTOM;

  protected readonly clock = computed(() => buildAwakeClock(this.periods()));
  private readonly range = computed(() => axisRange(this.periods().map(toTimingBar)));
  private x(pos: number): number {
    const r = this.range();
    return ((pos - r.from) / Math.max(r.to - r.from, 1)) * W;
  }

  protected readonly bins = computed<BinVM[]>(() => {
    const r = this.range();
    return this.clock().bins
      .filter((b) => b.to > r.from && b.from < r.to && b.nights > 0)
      .map((b) => {
        const x0 = this.x(Math.max(b.from, r.from));
        const x1 = this.x(Math.min(b.to, r.to));
        return { x: x0, w: Math.max(1, x1 - x0), opacity: awakeDensityOpacity(b.density) };
      });
  });

  protected readonly ticks = computed<TickVM[]>(() => {
    const r = this.range();
    const out: TickVM[] = [];
    for (let hh = Math.ceil(r.from / 2) * 2; hh <= r.to; hh += 2) {
      out.push({ x: this.x(hh), label: `${String((SLEEP_AXIS_ORIGIN_H + hh) % 24).padStart(2, '0')}h` });
    }
    return out;
  });

  protected readonly peakText = computed(() => {
    const c = this.clock();
    const peak = peakAwakeWindow(c);
    if (!peak) return `Sem horário que se repita nas ${c.nightsReporting} noites.`;
    const hour = Math.floor((SLEEP_AXIS_ORIGIN_H + peak.from) % 24);
    const min = Math.round((peak.from % 1) * 60);
    const hhmm = `${String(hour).padStart(2, '0')}:${String(min).padStart(2, '0')}`;
    return `Mais frequente por volta de ${hhmm} — em ${peak.nights} de ${c.nightsReporting} noites.`;
  });
}

// mobile/src/components/charts/AwakeningsClock.tsx
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import Svg, { Rect, Line, Text as SvgText } from 'react-native-svg';
import {
  SLEEP_AXIS_ORIGIN_H,
  awakeDensityOpacity,
  axisRange,
  buildAwakeClock,
  peakAwakeWindow,
  toTimingBar,
  type SleepPeriod,
} from '@vitale/shared';
import { colors, fonts, useThemedStyles } from '../../theme';

interface Props {
  periods: SleepPeriod[];
  width: number;
  height?: number;
  /** A cor da vigília — `sleepColors().awake`. Amarelo, como em toda tela de sono. */
  color: string;
}

const PAD_BOTTOM = 16;

/**
 * O relógio de vigília: os despertares de todas as noites da janela sobrepostos
 * num único eixo de hora do dia. Responde "eu acordo sempre às 3h?" — que nenhum
 * score da categoria responde — por DENSIDADE (faixas mais cheias onde mais
 * noites coincidem), não por contagem. É magnitude de vigília: o matiz é o da
 * vigília, e a opacidade faz o "quanto".
 *
 * Três estados, e a tela diz qual é: a fonte não reporta ("não sei"), reporta e
 * não houve, reporta e houve. Colapsar os dois primeiros em zero faria a tela
 * afirmar "você dormiu direto" quando a verdade é "não sei".
 *
 * Sem score, sem índice de fragmentação — o dado do usuário mostra vigília × nota
 * correndo ao contrário do que um score assumiria (spec §6).
 */
export function AwakeningsClock({ periods, width, height = 64, color }: Props) {
  const styles = useThemedStyles(createStyles);
  if (width <= 0) return null;

  const clock = buildAwakeClock(periods);

  if (clock.coverage === 'unreported') {
    return <Text style={styles.note}>Seu relógio não reporta despertares — não dá para saber.</Text>;
  }
  if (clock.coverage === 'none') {
    return <Text style={styles.note}>Nenhum despertar registrado nas últimas {clock.nightsReporting} noites.</Text>;
  }

  // Mesmo eixo do timing chart, para as duas leituras se alinharem.
  const range = axisRange(periods.map(toTimingBar));
  const span = Math.max(range.to - range.from, 1);
  const innerH = height - PAD_BOTTOM;
  const x = (pos: number) => ((pos - range.from) / span) * width;

  const gridStart = Math.ceil(range.from / 2) * 2;
  const grid: number[] = [];
  for (let h = gridStart; h <= range.to; h += 2) grid.push(h);

  const peak = peakAwakeWindow(clock);
  const hourOf = (pos: number) => `${String(Math.floor((SLEEP_AXIS_ORIGIN_H + pos) % 24)).padStart(2, '0')}:${String(Math.round(((pos % 1) + 1) % 1 * 60)).padStart(2, '0')}`;

  return (
    <View>
      <Svg width={width} height={height}>
        {clock.bins
          .filter((b) => b.to > range.from && b.from < range.to && b.nights > 0)
          .map((b) => (
            <Rect
              key={b.from}
              x={x(Math.max(b.from, range.from))}
              y={0}
              width={Math.max(1, x(Math.min(b.to, range.to)) - x(Math.max(b.from, range.from)))}
              height={innerH}
              fill={color}
              opacity={awakeDensityOpacity(b.density)}
            />
          ))}
        <Line x1={0} y1={innerH} x2={width} y2={innerH} stroke={colors.line} strokeWidth={1} />
        {grid.map((h) => (
          <SvgText key={h} x={x(h)} y={height - 3} fontSize={9} fill={colors.ink4} textAnchor="middle">
            {`${String((SLEEP_AXIS_ORIGIN_H + h) % 24).padStart(2, '0')}h`}
          </SvgText>
        ))}
      </Svg>
      <Text style={styles.note}>
        {peak
          ? `Mais frequente por volta de ${hourOf(peak.from)} — em ${peak.nights} de ${clock.nightsReporting} noites.`
          : `Sem horário que se repita nas ${clock.nightsReporting} noites.`}
      </Text>
    </View>
  );
}

const createStyles = () =>
  StyleSheet.create({
    note: { fontSize: 12, lineHeight: 17, color: colors.ink3, fontFamily: fonts.sans, marginTop: 6 },
  });
