// web/src/app/features/auth/register/register.component.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../../core/auth/auth.service';

@Component({
  selector: 'rt-register',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, RouterLink],
  templateUrl: './register.component.html',
  styleUrl: './register.component.scss',
})
export class RegisterComponent {
  private readonly auth = inject(AuthService);

  protected email = '';
  protected password = '';
  protected confirmPassword = '';
  protected loading = signal(false);
  protected error = signal<string | null>(null);
  protected success = signal(false);

  protected async submit(): Promise<void> {
    if (!this.email || !this.password) return;
    if (this.password !== this.confirmPassword) {
      this.error.set('As senhas não coincidem.');
      return;
    }
    this.loading.set(true);
    this.error.set(null);
    const err = await this.auth.signUp(this.email, this.password);
    if (err) {
      this.error.set(err);
    } else {
      this.success.set(true);
    }
    this.loading.set(false);
  }
}

<div class="page">
  <div class="card">
    <h1 class="logo">Rotina</h1>
    <p class="subtitle">Crie sua conta</p>

    @if (success()) {
      <div class="success">
        <p>Verifique seu e-mail para confirmar o cadastro.</p>
        <a routerLink="/login">Ir para o login →</a>
      </div>
    } @else {
      <form class="form" (ngSubmit)="submit()">
        <div class="field">
          <label for="email">E-mail</label>
          <input
            id="email"
            type="email"
            [(ngModel)]="email"
            name="email"
            placeholder="voce@email.com"
            autocomplete="email"
            required
          />
        </div>

        <div class="field">
          <label for="password">Senha</label>
          <input
            id="password"
            type="password"
            [(ngModel)]="password"
            name="password"
            placeholder="Mínimo 6 caracteres"
            autocomplete="new-password"
            required
          />
        </div>

        <div class="field">
          <label for="confirm">Confirmar senha</label>
          <input
            id="confirm"
            type="password"
            [(ngModel)]="confirmPassword"
            name="confirmPassword"
            placeholder="••••••••"
            autocomplete="new-password"
            required
          />
        </div>

        @if (error()) {
          <p class="error">{{ error() }}</p>
        }

        <button type="submit" class="btn-primary" [disabled]="loading()">
          {{ loading() ? 'Criando conta…' : 'Criar conta' }}
        </button>
      </form>

      <p class="footer-link">
        Já tem conta? <a routerLink="/login">Entrar</a>
      </p>
    }
  </div>
</div>

// mobile/src/app/(auth)/register.tsx
import { useState } from 'react';
import {
  View, Text, TextInput, TouchableOpacity,
  StyleSheet, KeyboardAvoidingView, Platform, ActivityIndicator, ScrollView,
} from 'react-native';
import { Link } from 'expo-router';
import { useAuthStore } from '../../store/auth.store';
import { colors, spacing, radii, fonts } from '../../theme';

export default function RegisterScreen() {
  const { signUp, loading } = useAuthStore();

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  const handleSubmit = async () => {
    if (!email || !password) return;
    if (password !== confirmPassword) {
      setError('As senhas não coincidem.');
      return;
    }
    setError(null);
    const err = await signUp(email, password);
    if (err) {
      setError(err);
    } else {
      setSuccess(true);
    }
  };

  return (
    <KeyboardAvoidingView
      style={s.page}
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
    >
      <ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled">
        <View style={s.card}>
          <Text style={s.logo}>Rotina</Text>
          <Text style={s.subtitle}>Crie sua conta</Text>

          {success ? (
            <View style={s.successBox}>
              <Text style={s.successText}>
                Verifique seu e-mail para confirmar o cadastro.
              </Text>
              <Link href="/(auth)/login" style={s.link}>
                Ir para o login →
              </Link>
            </View>
          ) : (
            <>
              <View style={s.field}>
                <Text style={s.label}>E-mail</Text>
                <TextInput
                  style={s.input}
                  value={email}
                  onChangeText={setEmail}
                  placeholder="voce@email.com"
                  placeholderTextColor={colors.ink3}
                  keyboardType="email-address"
                  autoCapitalize="none"
                  autoCorrect={false}
                />
              </View>

              <View style={s.field}>
                <Text style={s.label}>Senha</Text>
                <TextInput
                  style={s.input}
                  value={password}
                  onChangeText={setPassword}
                  placeholder="Mínimo 6 caracteres"
                  placeholderTextColor={colors.ink3}
                  secureTextEntry
                />
              </View>

              <View style={s.field}>
                <Text style={s.label}>Confirmar senha</Text>
                <TextInput
                  style={s.input}
                  value={confirmPassword}
                  onChangeText={setConfirmPassword}
                  placeholder="••••••••"
                  placeholderTextColor={colors.ink3}
                  secureTextEntry
                />
              </View>

              {error && (
                <View style={s.errorBox}>
                  <Text style={s.errorText}>{error}</Text>
                </View>
              )}

              <TouchableOpacity style={s.btn} onPress={handleSubmit} disabled={loading} activeOpacity={0.85}>
                {loading
                  ? <ActivityIndicator color="#fff" />
                  : <Text style={s.btnText}>Criar conta</Text>
                }
              </TouchableOpacity>

              <Text style={s.footerText}>
                Já tem conta?{' '}
                <Link href="/(auth)/login" style={s.link}>Entrar</Link>
              </Text>
            </>
          )}
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const s = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  scroll: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii['2xl'],
    padding: spacing['3xl'],
    width: '100%',
    maxWidth: 400,
  },
  logo: {
    fontFamily: fonts.serif,
    fontSize: 32,
    color: colors.primary,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  subtitle: {
    fontFamily: fonts.sans,
    fontSize: 14,
    color: colors.ink2,
    textAlign: 'center',
    marginBottom: spacing['2xl'],
  },
  field: {
    marginBottom: spacing.md,
  },
  label: {
    fontFamily: fonts.sans,
    fontSize: 13,
    fontWeight: '500',
    color: colors.ink,
    marginBottom: spacing.xs,
  },
  input: {
    height: 46,
    borderWidth: 1.5,
    borderColor: colors.line,
    borderRadius: radii.md,
    paddingHorizontal: spacing.md,
    fontSize: 14,
    fontFamily: fonts.sans,
    color: colors.ink,
    backgroundColor: colors.bg,
  },
  errorBox: {
    backgroundColor: '#fff0f0',
    borderRadius: radii.sm,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  errorText: {
    fontSize: 13,
    color: '#e05252',
    fontFamily: fonts.sans,
  },
  successBox: {
    alignItems: 'center',
    paddingVertical: spacing.xl,
    gap: spacing.md,
  },
  successText: {
    fontSize: 14,
    color: colors.ink,
    textAlign: 'center',
    fontFamily: fonts.sans,
  },
  btn: {
    height: 48,
    backgroundColor: colors.primary,
    borderRadius: radii.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.sm,
  },
  btnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    fontFamily: fonts.sans,
  },
  footerText: {
    fontSize: 13,
    color: colors.ink2,
    textAlign: 'center',
    marginTop: spacing.xl,
    fontFamily: fonts.sans,
  },
  link: {
    color: colors.primary,
    fontWeight: '500',
  },
});
