// web/src/app/features/retrospectiva/components/sleep-retro-card.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import {
  AWAKE_COUNTED_MIN,
  NIGHT_REFERENCE_H,
  clockOfAxis,
  coverageNote,
  formatHm,
  signedMin,
  type PeriodKind,
  type SleepRetro,
  type SleepTriggerBoard,
} from '@vitale/shared';
import { TypicalAwakeComponent } from '@features/sono/components/typical-awake.component';
import { SleepTriggersComponent } from './sleep-triggers.component';
import { SleepScoreDimsComponent } from '@features/sono/components/sleep-score-dims.component';

const NOUN: Record<PeriodKind, string> = {
  week: 'semana', month: 'mês', season: 'estação', year: 'ano', all: 'período',
};
const MES = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez'];

function dm(day: string): string {
  return `${Number(day.slice(8, 10))}/${day.slice(5, 7)}`;
}
function weekRange(key: string): string {
  const a = new Date(`${key}T12:00:00`);
  const b = new Date(a);
  b.setDate(a.getDate() + 6);
  return `${a.getDate()}–${b.getDate()} ${MES[b.getMonth()]}`;
}

/**
 * O bloco **Sono** da Retrospectiva na web — a mesma página do mobile,
 * recomposta em coluna. A web já calculava `summary.sleep` desde 05/09 e não a
 * desenhava; agora desenha, e com as seis pautas de 06/09 (ADR 0036).
 *
 * A ordem é de jornal: a tarja, o **selo** em caixa, e então o corpo — quanto,
 * quando, acordado e a que horas, por fase, as semanas, como acordou, e as duas
 * datas que fecham. Nenhum cálculo nasce aqui: tudo vem de `sleepRetro`.
 *
 * Três regras que o desenho carrega:
 * 1. **O número grande é a mediana**, e a média entra embaixo quando as duas
 *    discordam — publicar só a média é publicar o número errado quando uma noite
 *    curta puxa o período.
 * 2. **O selo não é a manchete.** Ele vem depois da tarja e antes do corpo.
 * 3. **Sem semáforo nas dimensões** e sem seta de tendência: as diferenças saem
 *    em minutos, que são fato.
 */
@Component({
  selector: 'rt-sleep-retro-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [SleepScoreDimsComponent, TypicalAwakeComponent, SleepTriggersComponent],
  template: `
    <div class="eyebrow">
      Sono <span class="n">· {{ r().cur.nights }} {{ r().cur.nights === 1 ? 'noite' : 'noites' }}</span>
    </div>

    @if (r().score; as sc) {
      <div class="seal">
        <div class="seal-t">Saúde do sono</div>
        <rt-sleep-score-dims [score]="sc" [note]="note()" />
      </div>
    }

    <div class="big">
      {{ hm(r().medianH) }}
      @if (d(); as dd) {
        <span class="big-delta" [attr.data-tone]="tone(dd.asleepMin, false, 5)">{{ sig(dd.asleepMin) }} vs {{ noun() }} anterior</span>
      }
    </div>
    <p class="muted">
      dormindo numa noite típica · {{ r().cur.nightsAtReference }} de {{ r().cur.nights }} com {{ REF }} h ou mais
    </p>
    @if (r().meanMedianSplit) {
      <p class="fine">
        a média foi {{ hm(r().cur.asleepH) }} — a noite de {{ dm(r().extremes.shortest.day) }},
        com {{ hm(r().extremes.shortest.h) }}, puxa sozinha
      </p>
    }

    <div class="row"><span>Apagou · acordou</span><span class="row-v mono">{{ clock(r().cur.onset.median) }} · {{ clock(r().cur.wake.median) }}</span></div>
    <p class="fine">
      medianas · miolo {{ clock(r().cur.onset.p25) }}–{{ clock(r().cur.onset.p75) }} e
      {{ clock(r().cur.wake.p25) }}–{{ clock(r().cur.wake.p75) }}
    </p>

    <p class="sub">Acordado — e a que horas</p>
    @if (r().cur.awake; as aw) {
      <div class="row"><span>Por noite</span><span class="row-v mono">{{ round(aw.minMean) }} min <small>· {{ aw.countMean.toFixed(1) }} despertares</small></span></div>
      @if (r().awakeSpread; as sp) {
        @if (sp.total > 0) {
          <div class="row"><span>De {{ COUNTED }} min para cima</span><span class="row-v mono">{{ sp.counted }} <small>de {{ sp.total }}</small></span></div>
        }
      }
      @if (r().typical; as t) {
        @if (t.medianMin !== null) {
          <rt-typical-awake [typical]="t" [longestDay]="t.longest ? dm(t.longest.day) : null" />
          <p class="fine">a duração de um despertar não muda de aparelho — a contagem, sim</p>
        }
      }
      @if (peak(); as pk) {
        <div class="hours">
          @for (h of r().awakeHours; track h.from) {
            <span class="hour">
              <span class="h-track"><span class="h-bar" [style.height.px]="barH(h.nights, pk.nights)" [style.opacity]="h.nights === pk.nights ? 1 : .42"></span></span>
              <span class="h-lab mono">{{ clock(h.from).slice(0, 2) }}</span>
            </span>
          }
        </div>
        <p class="fine">a noite quebrou mais entre {{ clock(pk.from) }} e {{ clock(pk.from + 1) }} — {{ pk.nights }} noites</p>
      }
    } @else {
      <p class="fine">a fonte não reporta despertares neste período</p>
    }

    @if (r().cur.stages; as st) {
      <p class="sub">Por fase — a noite média</p>
      <div class="stage">
        <i [style.flex]="st.rem" style="background:var(--sleep-rem)"></i>
        <i [style.flex]="st.core" style="background:var(--sleep-light)"></i>
        <i [style.flex]="st.deep" style="background:var(--sleep-deep)"></i>
        @if (r().cur.awake; as aw) { <i [style.flex]="aw.minMean / 60" style="background:var(--sleep-awake)"></i> }
      </div>
      <div class="key">
        <span><i style="background:var(--sleep-rem)"></i>REM {{ hm(st.rem) }}</span>
        <span><i style="background:var(--sleep-light)"></i>Leve {{ hm(st.core) }}</span>
        <span><i style="background:var(--sleep-deep)"></i>Profundo {{ hm(st.deep) }}</span>
        @if (r().cur.awake; as aw) { <span><i style="background:var(--sleep-awake)"></i>acordado {{ round(aw.minMean) }} min</span> }
      </div>
    }

    @if (showWeeks()) {
      <p class="sub">Semana a semana</p>
      <div class="weeks">
        @for (w of shownWeeks(); track w.key) {
          <span class="wk">
            <span class="wk-v mono">{{ hm(w.asleepH) }}</span>
            <span class="wk-track"><span class="wk-bar" [style.height.px]="wkH(w.asleepH)"></span></span>
            <span class="wk-l">{{ weekRange(w.key) }}</span>
            <span class="wk-n mono">n{{ w.nights }}</span>
          </span>
        }
      </div>
    }

    @if (showSri()) {
      <p class="sub">Regularidade, semana a semana</p>
      <div class="weeks">
        @for (w of sriWeeks(); track w.key) {
          <span class="wk">
            <span class="wk-v mono">{{ round(w.sri!) }}</span>
            <span class="wk-track"><span class="wk-bar deep" [style.height.px]="sriH(w.sri!)"></span></span>
            <span class="wk-l">{{ weekRange(w.key) }}</span>
            <span class="wk-n mono">n{{ w.nights }}</span>
          </span>
        }
      </div>
      <p class="fine">
        índice de 0 a 100 — a chance de você estar no mesmo estado 24 h depois. Abaixo de 72 fica o
        quintil de maior risco do UK Biobank.
      </p>
    }

    @if (r().ratings; as rt) {
      <p class="sub">Como você acordou</p>
      <div class="row"><span>Nota média</span><span class="row-v mono">{{ rt.mean.toFixed(1) }}/5 <small>· {{ rt.n }} noites</small></span></div>
      @if (rt.hi; as hi) {
        <div class="row"><span>Nota 4–5 ({{ hi.n }})</span><span class="row-v mono">{{ hm(hi.asleepH) }}</span></div>
      }
      @if (rt.lo; as lo) {
        <div class="row"><span>Nota ≤3 ({{ lo.n }})</span><span class="row-v mono">{{ hm(lo.asleepH) }}</span></div>
      }
      @if (showBands()) {
        <p class="fine">e por quanto você dormiu naquelas noites</p>
        @for (b of ratedBands(); track b.label) {
          <div class="row"><span>Noites de {{ b.label }} ({{ b.ratedNights }})</span><span class="row-v mono">{{ b.rating!.toFixed(2) }}</span></div>
        }
      }
    }

    <p class="sub">{{ nounCap() }} em duas datas</p>
    <div class="row">
      <span>{{ dm(r().extremes.shortest.day) }} — a mais curta</span>
      <span class="row-v mono">{{ hm(r().extremes.shortest.h) }}</span>
    </div>
    <div class="row">
      <span>{{ dm(r().extremes.longest.day) }} — a mais longa</span>
      <span class="row-v mono">{{ hm(r().extremes.longest.h) }}</span>
    </div>
    @if (r().extremes.best; as b) {
      <div class="row"><span>{{ dm(b.day) }} — a de maior contagem</span><span class="row-v mono">{{ b.points }}/{{ b.max }}</span></div>
    }

    @if (triggers(); as tb) {
      <div class="standing">
        <span class="tag">todo o histórico · não é {{ deste() }}</span>
        <p class="sub st">O que precedeu a noite</p>
        <rt-sleep-triggers [board]="tb" />
      </div>
    }

    <p class="fix">
      @if (r().prev; as p) { {{ nounCap() }} anterior: {{ p.nights }} {{ p.nights === 1 ? 'noite' : 'noites' }}. }
      @if (r().cur.stages) { Fases são estimativa do relógio, comparáveis com você mesmo. }
      @if (r().sourceChange; as m) { A comparação cruza a troca para {{ m.label }} ({{ dm(m.day) }}): despertares não se comparam. }
      @if (lowCoverage(); as c) { {{ c.nights }} de {{ c.expected }} noites gravadas — abaixo do piso, as medidas aparecem e a contagem não. }
    </p>
  `,
  styles: [`
    :host { display: block; }
    .eyebrow { font-size: 11px; font-weight: 700; letter-spacing: .06em; text-transform: uppercase; color: var(--ink-3); }
    .eyebrow .n { font-weight: 500; text-transform: none; letter-spacing: 0; }
    .mono { font-family: ui-monospace, Menlo, monospace; font-variant-numeric: tabular-nums; }

    .seal { background: var(--surface-mute); border: 1px solid var(--line); border-radius: 12px; padding: 12px 14px; margin: 10px 0 14px; }
    .seal-t { font-size: 10.5px; font-weight: 700; letter-spacing: .09em; text-transform: uppercase; color: var(--ink-3); }

    .big { font-size: 30px; font-weight: 700; color: var(--ink); display: flex; align-items: baseline; gap: 10px; flex-wrap: wrap; }
    .big-delta { font-size: 13px; font-weight: 600; }
    .big-delta[data-tone="good"] { color: var(--role-green-text, var(--ink-2)); }
    .big-delta[data-tone="bad"] { color: var(--role-red-text, var(--ink-2)); }
    .big-delta[data-tone="flat"] { color: var(--ink-3); }
    .muted { font-size: 13px; color: var(--ink-3); margin: 4px 0 8px; }
    .fine { font-size: 11.5px; line-height: 1.5; color: var(--ink-3); margin: 2px 0 8px; }
    .sub { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .05em; color: var(--ink-3); margin: 14px 0 4px; }
    .row { display: flex; align-items: baseline; justify-content: space-between; gap: 10px; padding: 5px 0; font-size: 13.5px; border-bottom: 1px solid var(--line); }
    .row:last-of-type { border-bottom: 0; }
    .row-v { font-weight: 600; }
    .row-v small { font-weight: 400; color: var(--ink-3); }

    .hours { display: flex; gap: 3px; align-items: flex-end; margin-top: 8px; }
    .hour { flex: 1; display: flex; flex-direction: column; align-items: center; }
    .h-track { height: 32px; width: 100%; display: flex; align-items: flex-end; justify-content: center; }
    .h-bar { width: 68%; border-radius: 2px; background: var(--sleep-awake); }
    .h-lab { font-size: 8.5px; color: var(--ink-4); margin-top: 3px; }

    .stage { display: flex; height: 16px; gap: 2px; border-radius: 4px; overflow: hidden; margin-top: 6px; }
    .stage i { display: block; }
    .key { display: flex; flex-wrap: wrap; gap: 4px 14px; font-size: 11.5px; color: var(--ink-2); margin-top: 8px; }
    .key i { display: inline-block; width: 9px; height: 9px; border-radius: 2px; margin-right: 5px; vertical-align: -1px; }

    .weeks { display: flex; gap: 6px; align-items: flex-end; margin-top: 6px; }
    .wk { flex: 1; display: flex; flex-direction: column; align-items: center; gap: 2px; min-width: 0; }
    .wk-v { font-size: 11px; color: var(--ink); }
    .wk-track { height: 44px; width: 100%; display: flex; align-items: flex-end; justify-content: center; }
    .wk-bar { width: 62%; border-radius: 3px; background: var(--sleep-sleep); }
    .wk-bar.deep { background: var(--sleep-deep); }
    .wk-l { font-size: 9.5px; color: var(--ink-3); white-space: nowrap; }
    .wk-n { font-size: 9px; color: var(--ink-4); }

    /* Os gatilhos falam de outra janela. O vão e a tarja avisam antes do número. */
    .standing { margin-top: 20px; padding-top: 14px; border-top: 1px solid var(--line); }
    .standing .tag { display: block; font-size: 9.5px; letter-spacing: .08em; text-transform: uppercase; color: var(--ink-4); font-weight: 600; }
    .sub.st { margin-top: 4px; }

    .fix { margin: 14px 0 0; padding-left: 12px; border-left: 2px solid var(--line-deep); font-size: 11.5px; line-height: 1.5; color: var(--ink-3); }
  `],
})
export class SleepRetroCardComponent {
  readonly retro = input.required<SleepRetro>();
  readonly kind = input.required<PeriodKind>();
  /** 'Total' não tem período anterior — as variações somem. */
  readonly noPrior = input(false);
  /**
   * O que precedeu a noite. Roda em todo o histórico, não no período — por isso
   * chega por fora de `retro`, que é do período. `null` esconde o bloco.
   */
  readonly triggers = input<SleepTriggerBoard | null>(null);

  protected readonly REF = NIGHT_REFERENCE_H;
  protected readonly COUNTED = AWAKE_COUNTED_MIN;
  protected readonly hm = formatHm;
  protected readonly sig = signedMin;
  protected readonly clock = clockOfAxis;
  protected readonly dm = dm;
  protected readonly weekRange = weekRange;
  protected readonly round = Math.round;

  protected readonly r = this.retro;
  protected readonly d = computed(() => (this.noPrior() ? null : this.retro().delta));
  protected readonly noun = computed(() => NOUN[this.kind()]);
  /** 'desta semana' | 'deste mês' — a tarja dos gatilhos concorda com o período. */
  protected readonly deste = computed(() => {
    const n = NOUN[this.kind()];
    return n === 'semana' || n === 'estação' ? `desta ${n}` : `deste ${n}`;
  });
  protected readonly nounCap = computed(() => {
    const n = this.noun();
    return n.charAt(0).toUpperCase() + n.slice(1);
  });
  protected readonly note = computed(() => {
    // Guardado, e não `score!`: o template só lê isto dentro do `@if`, mas um
    // sinal que explode quando lido fora dele é uma armadilha para quem editar.
    const s = this.retro().score;
    return s ? coverageNote(s) ?? undefined : undefined;
  });

  protected readonly peak = computed(() => {
    const hs = this.retro().awakeHours;
    if (hs.length < 3) return null;
    return hs.reduce((m, h) => (h.nights > m.nights ? h : m));
  });

  protected readonly shownWeeks = computed(() => this.retro().weeks.filter((w) => w.nights >= 3));
  protected readonly showWeeks = computed(() => {
    const k = this.kind();
    return (k === 'month' || k === 'season') && this.shownWeeks().length >= 2;
  });
  protected readonly sriWeeks = computed(() => this.retro().regularityWeeks.filter((w) => w.sri !== null));
  protected readonly showSri = computed(() => this.sriWeeks().length >= 2);
  protected readonly ratedBands = computed(() =>
    this.retro().bands.filter((b) => b.rating !== null && b.nights > 0),
  );
  protected readonly showBands = computed(() => this.ratedBands().length >= 2);

  protected readonly lowCoverage = computed(() => {
    const s = this.retro().score;
    return s && !s.scored && s.coverage && s.coverage.nights > 0 ? s.coverage : null;
  });

  protected readonly wkMax = computed(() => Math.max(9, ...this.shownWeeks().map((w) => w.asleepH)));
  protected wkH(h: number): number {
    return Math.max(3, (h / this.wkMax()) * 44);
  }
  protected sriH(v: number): number {
    return Math.max(3, (Math.max(0, v) / 100) * 44);
  }
  protected barH(n: number, peak: number): number {
    return Math.max(2, (n / peak) * 32);
  }

  protected tone(min: number, higherIsWorse: boolean, flat: number): 'good' | 'bad' | 'flat' {
    if (Math.abs(min) < flat) return 'flat';
    return (higherIsWorse ? min > 0 : min < 0) ? 'bad' : 'good';
  }
}

// mobile/src/components/SleepRetroCard.tsx
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import {
  AWAKE_COUNTED_MIN,
  NIGHT_REFERENCE_H,
  clockOfAxis,
  coverageNote,
  formatHm,
  signedMin,
  type PeriodKind,
  type SleepBand,
  type SleepBucket,
  type SleepRetro,
  type SleepTriggerBoard,
  type SleepWeekRegularity,
} from '@vitale/shared';
import { colors, fonts, radii, shadows, sleepColors, spacing, useThemedStyles } from '../theme';
import { CompositionBar } from './sono/BeforeAfter';
import { SleepScoreDims } from './sono/SleepScoreDims';
import { TypicalAwake } from './sono/TypicalAwake';
import { SleepTriggers } from './sono/SleepTriggers';

interface Props {
  retro: SleepRetro;
  kind: PeriodKind;
  /** 'Total' não tem período anterior — as variações somem. */
  noPrior: boolean;
  /**
   * O que precedeu a noite. Roda em todo o histórico, não no período — por isso
   * chega por fora de `retro`, que é do período. `null` esconde o bloco.
   */
  triggers?: SleepTriggerBoard | null;
}

const NOUN: Record<PeriodKind, string> = {
  week: 'semana', month: 'mês', season: 'estação', year: 'ano', all: 'período',
};
/** Dias do período — o "de 31 noites" da linha de amostra. `null` = não se sabe de antemão. */
function daysIn(kind: PeriodKind): number | null {
  return kind === 'week' ? 7 : null;
}
const MES = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez'];
function dm(day: string): string {
  return `${Number(day.slice(8, 10))}/${day.slice(5, 7)}`;
}
function weekRange(key: string): string {
  const a = new Date(`${key}T12:00:00`);
  const b = new Date(a);
  b.setDate(a.getDate() + 6);
  return `${a.getDate()}–${b.getDate()} ${MES[b.getMonth()]}`;
}

/**
 * O bloco **Sono** da Retrospectiva — a noite típica do período, dita em fatos.
 *
 * Segue a diagramação dos blocos vizinhos: número grande, linhas de fato, caixa
 * de correções. Cada linha responde uma pergunta de domingo: quanto dormi,
 * quando, quanto fiquei acordado, de que o sono foi feito, como acordei. As
 * diferenças saem em minutos; só as duas de cabeçalho (dormido, acordado) têm
 * tom, e o saldo contra uma meta ficou fora por decisão (05/09/2026).
 *
 * Tudo vem pronto de `sleepRetro` (shared): a tela só escreve. As cores são as
 * de `sleepColors()` — azul dorme, rosa sonha, amarelo acorda.
 */
export function SleepRetroCard({ retro, kind, noPrior, triggers }: Props) {
  const styles = useThemedStyles(createStyles);
  const sc = sleepColors();
  const {
    cur, prev, delta, ratings, weekend, weeks, sourceChange,
    score, medianH, meanMedianSplit, bands, awakeHours, awakeSpread, typical,
    regularityWeeks, extremes,
  } = retro;
  const d = noPrior ? null : delta;
  const noun = NOUN[kind];
  const days = daysIn(kind);

  const toneOf = (min: number, higherIsWorse: boolean, flat: number) => {
    if (Math.abs(min) < flat) return colors.ink3;
    const worse = higherIsWorse ? min > 0 : min < 0;
    return worse ? colors.redText : colors.greenText;
  };

  const aw = cur.awake;
  const st = cur.stages;
  const stageRows: { label: string; color: string; value: string; d: number | null }[] = st
    ? [
        { label: 'REM', color: sc.rem, value: formatHm(st.rem), d: d?.remMin ?? null },
        { label: 'Leve', color: sc.light, value: formatHm(st.core), d: d?.coreMin ?? null },
        { label: 'Profundo', color: sc.deep, value: formatHm(st.deep), d: d?.deepMin ?? null },
        ...(aw ? [{ label: 'Acordado', color: sc.awake, value: `${Math.round(aw.minMean)} min`, d: d?.awakeMin ?? null }] : []),
      ]
    : [];

  const showWeeks = (kind === 'month' || kind === 'season') && weeks.filter((w) => w.nights >= 3).length >= 2;
  const showWeekend = kind !== 'week' && weekend !== null;
  // A regularidade por semana precisa de duas semanas com índice: uma só é um
  // número solto, e o que a linha diz é a direção.
  const sriWeeks = regularityWeeks.filter((w) => w.sri !== null);
  const showSri = sriWeeks.length >= 2;
  // As faixas só falam quando há nota em duas delas — senão é contagem, não par.
  const ratedBands = bands.filter((b) => b.rating !== null && b.nights > 0);
  const showBands = ratedBands.length >= 2;
  const peakHour = awakeHours.length > 0 ? awakeHours.reduce((m, h) => (h.nights > m.nights ? h : m)) : null;

  return (
    <View style={styles.card}>
      <Text style={styles.eyebrow}>
        Sono <Text style={styles.eyebrowN}>· {cur.nights} {days ? `de ${days} ` : ''}{cur.nights === 1 ? 'noite' : 'noites'}</Text>
      </Text>

      {/* O selo — o resumo em caixa da página, DEPOIS da tarja e ANTES do corpo.
          Ele não é a manchete: a chamada continua sendo `sleepHighlights`. */}
      {score && (
        <View style={styles.seal}>
          <Text style={styles.sealTitle}>Saúde do sono</Text>
          <SleepScoreDims score={score} palette={sc} note={coverageNote(score) ?? undefined} />
        </View>
      )}

      {/* A MEDIANA é o número grande. A média entra na linha de baixo quando as
          duas discordam — esconder uma delas seria publicar o número errado. */}
      <Text style={styles.big}>
        {formatHm(medianH)}
        {d && prev && (
          <Text style={[styles.bigDelta, { color: toneOf(d.asleepMin, false, 5) }]}>  {signedMin(d.asleepMin)} vs {noun} anterior</Text>
        )}
      </Text>
      <Text style={styles.lab}>
        dormindo numa noite típica · {cur.nightsAtReference} de {cur.nights} com {NIGHT_REFERENCE_H} h ou mais
      </Text>
      {meanMedianSplit && (
        <Text style={styles.labTight}>
          a média foi {formatHm(cur.asleepH)} — a noite de {dm(extremes.shortest.day)}, com{' '}
          {formatHm(extremes.shortest.h)}, puxa sozinha
        </Text>
      )}

      <View style={styles.row}>
        <Text style={styles.rowL}>Apagou · acordou</Text>
        <Text style={styles.rowR}>{clockOfAxis(cur.onset.median)} · {clockOfAxis(cur.wake.median)}</Text>
      </View>
      <Text style={styles.labTight}>
        medianas · miolo {clockOfAxis(cur.onset.p25)}–{clockOfAxis(cur.onset.p75)} e {clockOfAxis(cur.wake.p25)}–{clockOfAxis(cur.wake.p75)}
      </Text>

      <Text style={styles.sub}>Acordado por noite</Text>
      {aw ? (
        <>
          <Text style={styles.mid}>
            {Math.round(aw.minMean)}<Text style={styles.unit}> min</Text>
            {d && d.awakeMin !== null && (
              <Text style={[styles.bigDelta, { color: toneOf(d.awakeMin, true, 3) }]}>  {signedMin(d.awakeMin)}</Text>
            )}
          </Text>
          <Text style={styles.lab}>
            {aw.countMean.toFixed(1).replace('.', ',')} despertares por noite · {aw.nightsWith} de {aw.reporting} noites com despertar
            {aw.longest ? ` · o mais longo ${Math.round(aw.longest.min)} min (${dm(aw.longest.day)} às ${clockOfAxis(aw.longest.at)})` : ''}
          </Text>
          {awakeSpread && awakeSpread.total > 0 && (
            <View style={styles.row}>
              <Text style={styles.rowL}>De {AWAKE_COUNTED_MIN} min para cima</Text>
              <Text style={styles.rowR}>{awakeSpread.counted}<Text style={styles.rowDelta}>  de {awakeSpread.total}</Text></Text>
            </View>
          )}
          {typical && typical.medianMin !== null && (
            <>
              <TypicalAwake
                typical={typical}
                palette={sc}
                longestDay={typical.longest ? dm(typical.longest.day) : undefined}
              />
              {/* A única leitura de vigília que atravessa a troca de relógio: a
                  contagem por noite cai 4× entre Apple e Garmin, a duração não. */}
              <Text style={styles.labTight}>
                a duração de um despertar não muda de aparelho — a contagem, sim
              </Text>
            </>
          )}
          {peakHour !== null && awakeHours.length >= 3 && (
            <>
              <HoursStrip hours={awakeHours} color={sc.awake} peak={peakHour.nights} />
              <Text style={styles.labTight}>
                a noite quebrou mais entre {clockOfAxis(peakHour.from)} e {clockOfAxis(peakHour.from + 1)} — {peakHour.nights} noites
              </Text>
            </>
          )}
        </>
      ) : (
        <Text style={styles.lab}>a fonte não reporta despertares neste período</Text>
      )}

      {st && (
        <>
          <Text style={styles.sub}>Por fase — a noite média</Text>
          <CompositionBar stages={st} awakeMin={aw?.minMean ?? null} palette={sc} />
          {stageRows.map((r) => (
            <View key={r.label} style={styles.row}>
              <View style={styles.rowLWrap}>
                <View style={[styles.dot, { backgroundColor: r.color }]} />
                <Text style={styles.rowL}>{r.label}</Text>
              </View>
              <Text style={styles.rowR}>
                {r.value}
                {r.d !== null && <Text style={styles.rowDelta}>  {signedMin(r.d)}</Text>}
              </Text>
            </View>
          ))}
        </>
      )}

      {showWeeks && <WeeksStrip weeks={weeks} color={sc.sleep} />}
      {showSri && <RegularityStrip weeks={sriWeeks} color={sc.deep} />}

      {showWeekend && weekend && (
        <>
          <Text style={styles.sub}>Fim de semana × semana</Text>
          <View style={styles.row}>
            <Text style={styles.rowL}>Meio do sono</Text>
            <Text style={styles.rowR}>{Math.abs(weekend.midpointLaterMin)} min mais {weekend.midpointLaterMin >= 0 ? 'tarde' : 'cedo'}</Text>
          </View>
          <Text style={styles.labTight}>
            {weekend.freeNights} noites livres · {weekend.workNights} de semana · acordar {signedMin(weekend.wakeLaterMin)} no fim de semana
          </Text>
        </>
      )}

      {ratings && (
        <>
          <Text style={styles.sub}>Como você acordou</Text>
          <View style={styles.row}>
            <Text style={styles.rowL}>
              <Text style={{ color: sc.sleep }}>{'●'.repeat(Math.round(ratings.mean))}</Text>
              <Text style={{ color: colors.ink4 }}>{'●'.repeat(5 - Math.round(ratings.mean))}</Text>
              <Text style={styles.rowMono}>  {ratings.mean.toFixed(1).replace('.', ',')}/5</Text>
            </Text>
            <Text style={styles.rowR}>{ratings.n} {ratings.n === 1 ? 'noite' : 'noites'} com nota</Text>
          </View>
          {ratings.hi && (
            <View style={styles.row}>
              <Text style={styles.rowL}>Nota 4–5 ({ratings.hi.n})</Text>
              <Text style={styles.rowR}>{formatHm(ratings.hi.asleepH)}{ratings.hi.awakeMin !== null ? ` · ${ratings.hi.awakeMin} min acordado` : ''}</Text>
            </View>
          )}
          {ratings.lo && (
            <View style={styles.row}>
              <Text style={styles.rowL}>Nota ≤3 ({ratings.lo.n})</Text>
              <Text style={styles.rowR}>{formatHm(ratings.lo.asleepH)}{ratings.lo.awakeMin !== null ? ` · ${ratings.lo.awakeMin} min acordado` : ''}</Text>
            </View>
          )}
          {/* O corte ao contrário: parte da DURAÇÃO e mostra a nota. É o que
              responde "vale a pena dormir mais?", que o corte por nota não responde. */}
          {showBands && (
            <>
              <Text style={styles.labTight}>e por quanto você dormiu naquelas noites</Text>
              {ratedBands.map((b) => (
                <View key={b.label} style={styles.row}>
                  <Text style={styles.rowL}>Noites de {b.label} ({b.ratedNights})</Text>
                  <Text style={styles.rowR}>{b.rating!.toFixed(2).replace('.', ',')}</Text>
                </View>
              ))}
            </>
          )}
        </>
      )}

      {/* As duas datas que fecham a página. Jornal nomeia — sem adjetivo. */}
      <Text style={styles.sub}>{noun.charAt(0).toUpperCase()}{noun.slice(1)} em duas datas</Text>
      <View style={styles.row}>
        <Text style={styles.rowL}>{dm(extremes.shortest.day)} — a mais curta</Text>
        <Text style={styles.rowR}>
          {formatHm(extremes.shortest.h)}
          {extremes.worst && extremes.worst.day === extremes.shortest.day && (
            <Text style={styles.rowDelta}>  {extremes.worst.points}/{extremes.worst.max}</Text>
          )}
        </Text>
      </View>
      <View style={styles.row}>
        <Text style={styles.rowL}>{dm(extremes.longest.day)} — a mais longa</Text>
        <Text style={styles.rowR}>
          {formatHm(extremes.longest.h)}
          {extremes.best && extremes.best.day === extremes.longest.day && (
            <Text style={styles.rowDelta}>  {extremes.best.points}/{extremes.best.max}</Text>
          )}
        </Text>
      </View>
      {extremes.best && extremes.best.day !== extremes.longest.day && (
        <View style={styles.row}>
          <Text style={styles.rowL}>{dm(extremes.best.day)} — a de maior contagem</Text>
          <Text style={styles.rowR}>{extremes.best.points}/{extremes.best.max}</Text>
        </View>
      )}

      {triggers && (
        <View style={styles.standing}>
          <Text style={styles.standingTag}>todo o histórico · não é deste {noun}</Text>
          <Text style={styles.sub}>O que precedeu a noite</Text>
          <SleepTriggers board={triggers} palette={sc} />
        </View>
      )}

      <Text style={styles.note}>
        {prev ? `${noun.charAt(0).toUpperCase()}${noun.slice(1)} anterior: ${prev.nights} ${prev.nights === 1 ? 'noite' : 'noites'}. ` : noPrior ? '' : `Sem noites no ${noun} anterior. `}
        {st ? 'Fases são estimativa do relógio, comparáveis com você mesmo. ' : ''}
        {sourceChange ? `A comparação cruza a troca para ${sourceChange.label} (${dm(sourceChange.day)}): despertares não se comparam. ` : ''}
        {score && !score.scored && score.coverage
          ? `${score.coverage.nights} de ${score.coverage.expected} noites gravadas — abaixo do piso, as medidas aparecem e a contagem não.`
          : ''}
      </Text>
    </View>
  );
}

/**
 * A que horas a noite quebrou — conta **noites**, não eventos: uma noite com
 * cinco micro-despertares às 3h vale uma, senão a barra mede o relógio.
 */
function HoursStrip({ hours, color, peak }: { hours: SleepRetro['awakeHours']; color: string; peak: number }) {
  const styles = useThemedStyles(createStyles);
  return (
    <View style={styles.hours}>
      {hours.map((h) => (
        <View key={h.from} style={styles.hour}>
          <View style={styles.hourTrack}>
            <View
              style={[
                styles.hourBar,
                {
                  height: Math.max(2, (h.nights / peak) * 30),
                  backgroundColor: color,
                  // O pico fica cheio; o resto recua, para o horário aparecer.
                  opacity: h.nights === peak ? 1 : 0.42,
                },
              ]}
            />
          </View>
          <Text style={styles.hourLab}>{clockOfAxis(h.from).slice(0, 2)}</Text>
        </View>
      ))}
    </View>
  );
}

/** A regularidade de cada semana — a única medida com evidência de desfecho. */
function RegularityStrip({ weeks, color }: { weeks: SleepWeekRegularity[]; color: string }) {
  const styles = useThemedStyles(createStyles);
  return (
    <>
      <Text style={styles.sub}>Regularidade, semana a semana</Text>
      <View style={styles.weeks}>
        {weeks.map((w) => (
          <View key={w.key} style={styles.week}>
            <Text style={styles.weekVal}>{Math.round(w.sri!)}</Text>
            <View style={styles.weekTrack}>
              <View style={[styles.weekBar, { height: Math.max(3, (Math.max(0, w.sri!) / 100) * 40), backgroundColor: color }]} />
            </View>
            <Text style={styles.weekLab}>{weekRange(w.key)}</Text>
            <Text style={styles.weekN}>n{w.nights}</Text>
          </View>
        ))}
      </View>
      <Text style={styles.labTight}>
        índice de 0 a 100 — a chance de você estar no mesmo estado 24 h depois. Abaixo de 72 fica o
        quintil de maior risco do UK Biobank.
      </Text>
    </>
  );
}

/** A noite média de cada semana do mês — para ver o mês mover. */
function WeeksStrip({ weeks, color }: { weeks: SleepBucket[]; color: string }) {
  const styles = useThemedStyles(createStyles);
  const shown = weeks.filter((w) => w.nights >= 3);
  const max = Math.max(9, ...shown.map((w) => w.asleepH));
  return (
    <>
      <Text style={styles.sub}>Semana a semana</Text>
      <View style={styles.weeks}>
        {shown.map((w) => (
          <View key={w.key} style={styles.week}>
            <Text style={styles.weekVal}>{formatHm(w.asleepH)}</Text>
            <View style={styles.weekTrack}>
              <View style={[styles.weekBar, { height: Math.max(3, (w.asleepH / max) * 40), backgroundColor: color }]} />
            </View>
            <Text style={styles.weekLab}>{weekRange(w.key)}</Text>
            <Text style={styles.weekN}>n{w.nights}{w.awakeMin !== null ? ` · ${Math.round(w.awakeMin)} min` : ''}</Text>
          </View>
        ))}
      </View>
    </>
  );
}

const createStyles = () =>
  StyleSheet.create({
    card: { backgroundColor: colors.surface, borderRadius: radii['2xl'], padding: spacing.lg, gap: 4, ...shadows.card },
    eyebrow: { fontSize: 11, fontFamily: fonts.sansBold, textTransform: 'uppercase', letterSpacing: 1.1, color: colors.ink3, marginBottom: 4 },
    eyebrowN: { textTransform: 'none', letterSpacing: 0, fontFamily: fonts.sansMedium },
    big: { fontSize: 28, fontFamily: fonts.mono, color: colors.ink, letterSpacing: -0.5 },
    mid: { fontSize: 22, fontFamily: fonts.mono, color: colors.ink, letterSpacing: -0.3 },
    unit: { fontSize: 13, color: colors.ink3, fontFamily: fonts.sans },
    bigDelta: { fontSize: 13, fontFamily: fonts.sansSemiBold, letterSpacing: 0 },
    lab: { fontSize: 12.5, color: colors.ink3, fontFamily: fonts.sans, lineHeight: 17 },
    labTight: { fontSize: 12, color: colors.ink3, fontFamily: fonts.sans, marginTop: -4 },
    sub: { fontSize: 12.5, fontFamily: fonts.sansBold, color: colors.ink2, marginTop: spacing.md, marginBottom: 2 },
    // Os gatilhos falam de outra janela. O vão e a tarja avisam antes do número.
    standing: { marginTop: spacing.lg, paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.line },
    standingTag: {
      fontSize: 9.5, letterSpacing: 0.8, textTransform: 'uppercase',
      color: colors.ink4, fontFamily: fonts.sansSemiBold,
    },
    row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: spacing.sm, paddingVertical: 7, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.line },
    rowLWrap: { flexDirection: 'row', alignItems: 'center', gap: 7 },
    dot: { width: 9, height: 9, borderRadius: 2 },
    rowL: { fontSize: 13.5, color: colors.ink2, fontFamily: fonts.sans },
    rowR: { fontSize: 13.5, color: colors.ink, fontFamily: fonts.mono, textAlign: 'right' },
    rowDelta: { fontSize: 12, color: colors.ink3, fontFamily: fonts.sans },
    rowMono: { fontSize: 12, fontFamily: fonts.mono, color: colors.ink },
    note: { fontSize: 11.5, lineHeight: 16, color: colors.ink3, fontFamily: fonts.sans, marginTop: spacing.md, paddingTop: spacing.sm, borderTopWidth: 1, borderTopColor: colors.line, borderStyle: 'dashed' },
    seal: {
      backgroundColor: colors.surfaceMute,
      borderRadius: radii.md,
      borderWidth: 1,
      borderColor: colors.line,
      padding: spacing.md,
      marginTop: spacing.sm,
      marginBottom: spacing.md,
    },
    sealTitle: { fontSize: 10.5, letterSpacing: 0.9, textTransform: 'uppercase', color: colors.ink3, fontFamily: fonts.sansBold },

    hours: { flexDirection: 'row', gap: 3, alignItems: 'flex-end', marginTop: spacing.sm },
    hour: { flex: 1, alignItems: 'center' },
    hourTrack: { height: 30, width: '100%', justifyContent: 'flex-end', alignItems: 'center' },
    hourBar: { width: '68%', borderRadius: 2 },
    hourLab: { fontSize: 8, color: colors.ink4, fontFamily: fonts.mono, marginTop: 3 },

    weeks: { flexDirection: 'row', gap: 6, alignItems: 'flex-end', marginTop: 4 },
    week: { flex: 1, alignItems: 'center' },
    weekVal: { fontSize: 10, fontFamily: fonts.mono, color: colors.ink2, marginBottom: 2 },
    weekTrack: { height: 40, width: '100%', justifyContent: 'flex-end', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.line },
    weekBar: { width: '60%', borderRadius: 3 },
    weekLab: { fontSize: 9.5, color: colors.ink3, fontFamily: fonts.mono, marginTop: 4 },
    weekN: { fontSize: 9, color: colors.ink4, fontFamily: fonts.mono },
  });
