// mobile/src/components/MonthCalendar.tsx
import React, { useMemo, useState } from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors, radii, spacing } from '../theme';
import { localDateStr } from '@vitale/shared';

const WEEKDAYS = ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'];
const MONTHS = [
  'janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho',
  'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro',
];

interface Cell {
  key: string;
  date: string; // '' = vazio
  day: number;
  marked: boolean;
  future: boolean;
}

interface Props {
  selected: string | null;
  marked?: Set<string>;
  onSelect: (date: string) => void;
  onMonthChange?: (year: number, monthIdx: number) => void;
}

/** Calendário mensal: grade 7 col (domingo→sábado), navegação de mês, futuro off. */
export function MonthCalendar({ selected, marked, onSelect, onMonthChange }: Props) {
  const now = useMemo(() => new Date(), []);
  const today = localDateStr(now);
  const [year, setYear] = useState(now.getFullYear());
  const [month, setMonth] = useState(now.getMonth());

  const canNext =
    year < now.getFullYear() || (year === now.getFullYear() && month < now.getMonth());

  const cells = useMemo<Cell[]>(() => {
    const first = new Date(year, month, 1).getDay();
    const total = new Date(year, month + 1, 0).getDate();
    const out: Cell[] = [];
    for (let i = 0; i < first; i++) out.push({ key: `e${i}`, date: '', day: 0, marked: false, future: false });
    for (let d = 1; d <= total; d++) {
      const date = localDateStr(new Date(year, month, d));
      out.push({ key: date, date, day: d, marked: !!marked?.has(date), future: date > today });
    }
    return out;
  }, [year, month, marked, today]);

  const step = (delta: number) => {
    if (delta > 0 && !canNext) return;
    let m = month + delta;
    let y = year;
    if (m < 0) { m = 11; y--; }
    else if (m > 11) { m = 0; y++; }
    setMonth(m);
    setYear(y);
    onMonthChange?.(y, m);
  };

  return (
    <View style={styles.cal}>
      <View style={styles.nav}>
        <Pressable onPress={() => step(-1)} hitSlop={8} style={({ pressed }) => [styles.navBtn, pressed && styles.pressed]}>
          <Ionicons name="chevron-back" size={18} color={colors.ink2} />
        </Pressable>
        <Text style={styles.label}>{MONTHS[month]} {year}</Text>
        <Pressable
          onPress={() => step(1)}
          disabled={!canNext}
          hitSlop={8}
          style={({ pressed }) => [styles.navBtn, pressed && styles.pressed, !canNext && styles.disabled]}
        >
          <Ionicons name="chevron-forward" size={18} color={colors.ink2} />
        </Pressable>
      </View>

      <View style={styles.row}>
        {WEEKDAYS.map((w, i) => (
          <View key={`wd${i}`} style={styles.cellWrap}>
            <Text style={styles.weekday}>{w}</Text>
          </View>
        ))}
      </View>

      <View style={styles.grid}>
        {cells.map((c) => {
          if (!c.date) return <View key={c.key} style={styles.cellWrap} />;
          const isSel = c.date === selected;
          const isToday = c.date === today;
          return (
            <View key={c.key} style={styles.cellWrap}>
              <Pressable
                onPress={() => onSelect(c.date)}
                disabled={c.future}
                style={({ pressed }) => [
                  styles.day,
                  isToday && styles.dayToday,
                  isSel && styles.daySel,
                  pressed && !isSel && styles.pressed,
                ]}
              >
                <Text style={[styles.dayNum, c.future && styles.dayFuture, isSel && styles.dayNumSel]}>
                  {c.day}
                </Text>
                {c.marked && <View style={[styles.dot, isSel && styles.dotSel]} />}
              </Pressable>
            </View>
          );
        })}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  cal: { backgroundColor: colors.surface, borderRadius: radii.xl, padding: spacing.md, borderWidth: 1, borderColor: colors.line },
  nav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.sm },
  navBtn: { width: 32, height: 32, borderRadius: radii.sm, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' },
  label: { fontSize: 14.5, fontWeight: '700', color: colors.ink, textTransform: 'capitalize' },
  pressed: { opacity: 0.6 },
  disabled: { opacity: 0.4 },
  row: { flexDirection: 'row', marginBottom: 4 },
  grid: { flexDirection: 'row', flexWrap: 'wrap' },
  cellWrap: { width: `${100 / 7}%`, aspectRatio: 1, padding: 2 },
  weekday: { textAlign: 'center', fontSize: 11, fontWeight: '600', color: colors.ink3 },
  day: { flex: 1, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' },
  dayToday: { borderWidth: 1, borderColor: colors.line },
  daySel: { backgroundColor: colors.primary },
  dayNum: { fontSize: 14, color: colors.ink, fontWeight: '500' },
  dayNumSel: { color: '#fff', fontWeight: '700' },
  dayFuture: { color: colors.ink4 },
  dot: { position: 'absolute', bottom: 5, width: 4, height: 4, borderRadius: 2, backgroundColor: colors.primary },
  dotSel: { backgroundColor: '#fff' },
});

// web/src/app/features/habits/components/month-calendar.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';
import { IconComponent } from '@core/services/icon.component';
import { localDateStr } from '@vitale/shared';

interface DayCell {
  date: string;        // 'YYYY-MM-DD' ('' = célula vazia de preenchimento)
  day: number;
  marked: boolean;
  future: boolean;
}

const WEEKDAYS = ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'];
const MONTHS = [
  'janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho',
  'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro',
];

/**
 * Calendário mensal: grade de 7 colunas (domingo→sábado), navegação ◀ mês ▶.
 * Datas futuras desabilitadas. Emite a data escolhida e o mês visualizado.
 */
@Component({
  selector: 'rt-month-calendar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [IconComponent],
  template: `
    <div class="cal">
      <div class="nav">
        <button class="navbtn" type="button" (click)="step(-1)" aria-label="Mês anterior">
          <rt-icon name="chev-l" [size]="18" color="var(--ink-2)" [strokeWidth]="2.2" />
        </button>
        <span class="label">{{ monthLabel() }}</span>
        <button class="navbtn" type="button" [disabled]="!canNext()" (click)="step(1)" aria-label="Próximo mês">
          <rt-icon name="chev-r" [size]="18" color="var(--ink-2)" [strokeWidth]="2.2" />
        </button>
      </div>

      <div class="grid head">
        @for (w of weekdays; track $index) { <span class="wd">{{ w }}</span> }
      </div>
      <div class="grid">
        @for (c of cells(); track $index) {
          @if (c.date) {
            <button
              class="day"
              type="button"
              [class.sel]="c.date === selected()"
              [class.today]="c.date === today"
              [disabled]="c.future"
              (click)="daySelected.emit(c.date)"
            >
              <span class="n">{{ c.day }}</span>
              @if (c.marked) { <span class="dot"></span> }
            </button>
          } @else {
            <span class="day empty"></span>
          }
        }
      </div>
    </div>
  `,
  styles: [`
    :host { display: block; }
    .cal {
      background: var(--surface); border: 1px solid var(--line);
      border-radius: 18px; padding: 14px; box-shadow: var(--shadow-card);
    }
    .nav { display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px; }
    .label { font-size: 14.5px; font-weight: 650; color: var(--ink); text-transform: capitalize; }
    .navbtn {
      width: 32px; height: 32px; border-radius: 9px; border: 1px solid var(--line);
      background: var(--surface); cursor: pointer; display: flex; align-items: center; justify-content: center;
    }
    .navbtn:hover { background: var(--surface-mute); }
    .navbtn:disabled { opacity: 0.4; cursor: default; }
    .grid { display: grid; grid-template-columns: repeat(7, 1fr); gap: 4px; }
    .grid.head { margin-bottom: 4px; }
    .wd { text-align: center; font-size: 11px; font-weight: 600; color: var(--ink-3); padding: 2px 0; }
    .day {
      position: relative; aspect-ratio: 1; border: 0; background: transparent; border-radius: 10px;
      cursor: pointer; font-size: 13.5px; color: var(--ink); display: flex;
      align-items: center; justify-content: center;
    }
    .day:hover:not(:disabled):not(.empty) { background: var(--surface-mute); }
    .day:disabled { color: var(--ink-4); cursor: default; }
    .day.empty { cursor: default; }
    .day.today { font-weight: 700; box-shadow: inset 0 0 0 1px var(--line); }
    .day.sel { background: var(--primary); color: #fff; font-weight: 700; }
    .dot {
      position: absolute; bottom: 5px; left: 50%; transform: translateX(-50%);
      width: 4px; height: 4px; border-radius: 50%; background: var(--primary);
    }
    .day.sel .dot { background: #fff; }
  `],
})
export class MonthCalendarComponent {
  readonly selected = input<string | null>(null);
  readonly marked = input<Set<string>>(new Set<string>());

  readonly daySelected = output<string>();
  readonly monthChanged = output<{ year: number; monthIdx: number }>();

  protected readonly weekdays = WEEKDAYS;
  protected readonly today = localDateStr();

  private readonly now = new Date();
  protected readonly viewYear = signal(this.now.getFullYear());
  protected readonly viewMonth = signal(this.now.getMonth());

  protected readonly monthLabel = computed(() => `${MONTHS[this.viewMonth()]} ${this.viewYear()}`);

  /** Bloqueia avançar para meses futuros. */
  protected readonly canNext = computed(() => {
    const y = this.viewYear(), m = this.viewMonth();
    return y < this.now.getFullYear() || (y === this.now.getFullYear() && m < this.now.getMonth());
  });

  protected readonly cells = computed<DayCell[]>(() => {
    const y = this.viewYear(), m = this.viewMonth();
    const marks = this.marked();
    const first = new Date(y, m, 1).getDay();           // 0=domingo
    const total = new Date(y, m + 1, 0).getDate();
    const out: DayCell[] = [];
    for (let i = 0; i < first; i++) out.push({ date: '', day: 0, marked: false, future: false });
    for (let d = 1; d <= total; d++) {
      const date = localDateStr(new Date(y, m, d));
      out.push({ date, day: d, marked: marks.has(date), future: date > this.today });
    }
    return out;
  });

  protected step(delta: number): void {
    if (delta > 0 && !this.canNext()) return;
    let m = this.viewMonth() + delta;
    let y = this.viewYear();
    if (m < 0) { m = 11; y--; }
    else if (m > 11) { m = 0; y++; }
    this.viewMonth.set(m);
    this.viewYear.set(y);
    this.monthChanged.emit({ year: y, monthIdx: m });
  }
}
