// mobile/src/components/sono/FactsList.tsx
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import type { Fact } from '@vitale/shared';
import { colors, fonts, spacing, useThemedStyles } from '../../theme';

/**
 * As análises sob um gráfico — fatos, não notas. Medianas com faixa, contagens,
 * diferenças. Vêm prontas do núcleo (`facts.ts`); aqui só se listam.
 */
export function FactsList({ facts }: { facts: Fact[] }) {
  const styles = useThemedStyles(createStyles);
  if (facts.length === 0) return null;
  return (
    <View style={styles.list}>
      {facts.map((f) => (
        <View key={f.label} style={styles.row}>
          <Text style={styles.label}>{f.label}</Text>
          <Text style={styles.value}>{f.value}</Text>
        </View>
      ))}
    </View>
  );
}

const createStyles = () =>
  StyleSheet.create({
    list: { marginTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: spacing.sm, gap: 7 },
    row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: spacing.sm },
    label: { flex: 1, fontSize: 12.5, color: colors.ink2, fontFamily: fonts.sans },
    value: { fontSize: 12.5, color: colors.ink, fontFamily: fonts.mono, textAlign: 'right', flexShrink: 0 },
  });

// web/src/app/features/sono/components/facts-list.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import type { Fact } from '@vitale/shared';

/**
 * As análises sob um gráfico — fatos, não notas. Medianas com faixa, contagens,
 * diferenças. Vêm prontas do núcleo (`facts.ts`); aqui só se listam.
 */
@Component({
  selector: 'rt-facts-list',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (facts().length > 0) {
      <div class="list">
        @for (f of facts(); track f.label) {
          <div class="row"><span class="label">{{ f.label }}</span><span class="value mono">{{ f.value }}</span></div>
        }
      </div>
    }
  `,
  styles: [`
    :host { display: block; }
    .list { margin-top: 12px; border-top: 1px solid var(--line); padding-top: 8px; display: grid; gap: 7px; }
    .row { display: flex; justify-content: space-between; align-items: flex-start; gap: 10px; font-size: 12.5px; }
    .label { color: var(--ink-2); }
    .value { color: var(--ink); text-align: right; flex-shrink: 0; }
  `],
})
export class FactsListComponent {
  readonly facts = input.required<Fact[]>();
}
