// mobile/src/components/sono/PeriodNav.tsx
import React from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SONO_RANGES, hasNights, rangeLabel, type SleepPeriod, type SonoRange } from '@vitale/shared';
import { Segmented } from '../ui/Segmented';
import { colors, fonts, spacing, useThemedStyles } from '../../theme';

interface Props {
  range: SonoRange;
  offset: number;
  /** Todas as noites conhecidas — é o que decide se o ◀ acende. */
  periods: SleepPeriod[];
  /** As noites da janela corrente, para o rótulo de "última". */
  nights: SleepPeriod[];
  onRange: (r: SonoRange) => void;
  onOffset: (o: number) => void;
}

const OPTIONS = SONO_RANGES.map((r) => ({ key: r.id, label: r.label }));

/**
 * O seletor de período das subviews de sono: o `Segmented` do Histórico (não um
 * primo) mais a navegação ◀ ▶ — um período do próprio tamanho para trás ou para
 * a frente, e o ◀ só acende onde há noite. Trocar o período volta ao corrente.
 */
export function PeriodNav({ range, offset, periods, nights, onRange, onOffset }: Props) {
  const styles = useThemedStyles(createStyles);
  const canBack = hasNights(periods, range, new Date(), offset + 1);
  const canFwd = offset > 0;
  return (
    <View>
      <Segmented
        options={OPTIONS}
        value={range}
        onChange={(r) => {
          onRange(r);
          onOffset(0);
        }}
      />
      <View style={styles.navRow}>
        <Pressable onPress={() => canBack && onOffset(offset + 1)} disabled={!canBack} hitSlop={10} style={styles.navBtn}>
          <Ionicons name="chevron-back" size={18} color={canBack ? colors.ink : colors.ink4} />
        </Pressable>
        <Text style={styles.navLabel}>{rangeLabel(range, nights, new Date(), offset)}</Text>
        <Pressable onPress={() => canFwd && onOffset(offset - 1)} disabled={!canFwd} hitSlop={10} style={styles.navBtn}>
          <Ionicons name="chevron-forward" size={18} color={canFwd ? colors.ink : colors.ink4} />
        </Pressable>
      </View>
    </View>
  );
}

const createStyles = () =>
  StyleSheet.create({
    navRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.sm },
    navBtn: { width: 34, height: 30, alignItems: 'center', justifyContent: 'center' },
    navLabel: { fontSize: 12.5, fontFamily: fonts.mono, color: colors.ink2 },
  });

// web/src/app/features/sono/components/period-nav.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { SONO_RANGES, hasNights, rangeLabel, type SleepPeriod, type SonoRange } from '@vitale/shared';
import { SonoSegmentedComponent, type SegOption } from './sono-segmented.component';

/**
 * O seletor de período das subviews de sono, como no mobile: o segmentado mais a
 * navegação ◀ ▶ — um período do próprio tamanho para trás ou para a frente, e o
 * ◀ só acende onde há noite. Trocar o período volta ao corrente.
 */
@Component({
  selector: 'rt-sono-period-nav',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [SonoSegmentedComponent],
  template: `
    <rt-sono-segmented [options]="options" [value]="range()" [full]="true" (select)="pick($event)" />
    <div class="nav">
      <button type="button" class="chev" [disabled]="!canBack()" (click)="offsetChange.emit(offset() + 1)" aria-label="período anterior">‹</button>
      <span class="label mono">{{ label() }}</span>
      <button type="button" class="chev" [disabled]="!canFwd()" (click)="offsetChange.emit(offset() - 1)" aria-label="período seguinte">›</button>
    </div>
  `,
  styles: [`
    :host { display: block; }
    rt-sono-segmented { display: block; }
    .nav { display: flex; align-items: center; justify-content: space-between; margin-top: 8px; }
    .chev { width: 34px; height: 30px; border: 0; background: transparent; color: var(--ink); font-size: 20px; line-height: 1; cursor: pointer; border-radius: 8px; }
    .chev:hover:not(:disabled) { background: var(--surface-mute); }
    .chev:disabled { color: var(--ink-4); cursor: default; }
    .chev:focus-visible { outline: 2px solid var(--primary); outline-offset: -2px; }
    .label { font-size: 12.5px; color: var(--ink-2); }
  `],
})
export class SonoPeriodNavComponent {
  readonly range = input.required<SonoRange>();
  readonly offset = input.required<number>();
  /** Todas as noites conhecidas — é o que decide se o ◀ acende. */
  readonly periods = input.required<SleepPeriod[]>();
  /** As noites da janela corrente, para o rótulo de "última". */
  readonly nights = input.required<SleepPeriod[]>();
  readonly rangeChange = output<SonoRange>();
  readonly offsetChange = output<number>();

  protected readonly options: SegOption[] = SONO_RANGES.map((r) => ({ value: r.id, label: r.label }));
  protected readonly canBack = computed(() => hasNights(this.periods(), this.range(), new Date(), this.offset() + 1));
  protected readonly canFwd = computed(() => this.offset() > 0);
  protected readonly label = computed(() => rangeLabel(this.range(), this.nights(), new Date(), this.offset()));

  protected pick(v: string): void {
    this.rangeChange.emit(v as SonoRange);
  }
}
