// mobile/src/components/charts/StackedBarChart.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ScrollView, AccessibilityInfo } from 'react-native';
import Svg, { Rect, Text as SvgText, Line, Path, Circle, Defs, LinearGradient, Stop } from 'react-native-svg';
import { compactNumber, niceAxisMax, remapChartColor, smoothLinePath, type LinePoint } from '@vitale/shared';
import type { OverviewBucket, Metric } from '../../lib/activity-overview';
import { formatDuration, formatDistance } from '../../lib/workout-format';
import { useChartPaletteStore } from '../../store/chart-palette.store';
import { colors } from '../../theme';

interface Props {
  buckets: OverviewBucket[];
  metric: Metric;
  width: number;
  height?: number;
  /** Quando true, ignora MIN_SLOT e comprime as barras para caber na largura disponível sem rolagem. */
  noScroll?: boolean;
  /** Muda quando período/métrica trocam — usado só para fechar o tooltip aberto.
   * A animação em si dispara sozinha a cada mudança dos dados (período/métrica/legenda). */
  animationKey?: string;
  /** Meta de referência (mesma unidade das barras); ausente = sem linha. */
  goal?: number;
  /** Rótulo da linha de meta (ex.: "OMS"). */
  goalLabel?: string;
  /** Sufixo de unidade do rótulo ("/mês"): sem ele "14h" é lido como total do período. */
  goalUnit?: string;
  /**
   * Meta do bucket em curso, proporcional ao tempo decorrido. Quando presente, a linha
   * da meta desce em degrau sobre esse bucket — comparar um mês pela metade com a meta
   * cheia faria a última barra parecer sempre um fracasso.
   */
  currentGoal?: number;
  /** Desenha a polilinha de esforço ponderado a partir de `bucket.effectiveS`. */
  showEffort?: boolean;
  /**
   * Reta horizontal com o esforço médio por bucket. Combina com `showEffort`: a
   * polilinha mostra a variação, a reta mostra o patamar médio para comparar direto
   * com a meta. No período "Semana" aparece sozinha (lá não há progressão).
   */
  effortFlat?: number;
  /** Rótulo da reta de média. */
  effortFlatLabel?: string;
  /** Cor da reta de média (esquema configurável em Preferências). */
  effortFlatColor?: string;
  /** Cor da polilinha de progressão. */
  effortColor?: string;
}

const PAD_TOP = 16;
const PAD_BOTTOM = 22;
const PAD_LEFT = 36;
const MIN_SLOT = 44; // largura mínima por barra antes de habilitar rolagem horizontal
const TOP_RADIUS = 7; // raio dos cantos superiores do segmento do topo da pilha
const ANIM_MS = 360;
/** Divisões do eixo Y: 4 passos = 5 linhas de grade (com a do zero). */
const GRID_TICKS = 4;
/** Unidade em que cada métrica é lida — o eixo escolhe passos redondos nela. */
const AXIS_UNIT: Record<Metric, number> = { distance: 1000, duration: 3600, calories: 1, count: 1 };
/** Métricas sem casa decimal: o passo do eixo tem que ser inteiro. */
const INTEGER_METRICS: ReadonlySet<Metric> = new Set<Metric>(['calories', 'count']);

// Tom quente usado para suavizar/clarear as cores das séries (casa com a paleta bege/creme).
const WARM = '#FBF1E2';

interface Seg { x: number; y: number; w: number; h: number; color: string; label: string; value: number; opacity: number; top: boolean; }
interface Bar {
  key: string; label: string; center: number; barW: number; x: number; comparison: boolean;
  total: number; topY: number; segs: Seg[];
  /** Y do ponto de esforço ponderado; `null` = bucket sem ponto (comparação / série desligada). */
  effY: number | null;
  /** Valor do esforço em segundos, para o tooltip. */
  effS: number;
}
interface SlotLayout { x0: number; slot: number; center: number; }
interface Model {
  chartW: number; baseY: number; layout: SlotLayout[];
  /** `base` = linha do zero: fecha o painel do plot, então tem traço mais firme. */
  grid: { y: number; label: string; base: boolean }[]; bars: Bar[];
  /** Path da linha de meta (reta ou com degrau no bucket em curso); '' = sem meta. */
  goalPath: string;
  /** Y da meta cheia, p/ posicionar o rótulo. */
  goalY: number | null;
  /** Y da reta de esforço médio; `null` = sem reta (série ou métrica não-duração). */
  effortFlatY: number | null;
}

/** Formata o valor do eixo Y de acordo com a métrica selecionada. */
function fmtAxis(v: number, metric: Metric): string {
  switch (metric) {
    case 'distance':
      return `${(v / 1000).toFixed(v >= 10000 ? 0 : 1)}km`;
    case 'duration':
      return `${(v / 3600).toFixed(v >= 36000 ? 0 : 1)}h`;
    case 'calories':
    case 'count':
      // "17426" rouba largura do eixo e não informa mais que "17k".
      return compactNumber(v);
  }
}

/**
 * Rótulo de valores pequenos: `fmtAxis` de duração sempre imprime horas, e a meta
 * diária (~21 min) viraria "0.4h". Abaixo de 1h usa minutos.
 */
function fmtCompact(v: number, metric: Metric): string {
  if (metric !== 'duration' || v >= 3600) return fmtAxis(v, metric);
  return `${Math.round(v / 60)} min`;
}

/** Valor exato de uma série (usado no tooltip). */
function fmtValue(v: number, metric: Metric): string {
  switch (metric) {
    case 'distance':
      return formatDistance(v) ?? '0 m';
    case 'duration':
      return formatDuration(v);
    case 'calories':
      return `${Math.round(v)} kcal`;
    case 'count':
      return `${Math.round(v)}`;
  }
}

// ---- Utilidades de cor (mix hex→hex, sem dependência) ----
const HEX_RE = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;
function isHex(c: string): boolean { return HEX_RE.test(c); }
function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  const full = h.length === 3 ? h.split('').map((c) => c + c).join('') : h;
  const n = parseInt(full, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}
function rgbToHex(r: number, g: number, b: number): string {
  const to = (v: number) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0');
  return `#${to(r)}${to(g)}${to(b)}`;
}
function mix(hex: string, withHex: string, amount: number): string {
  const [r1, g1, b1] = hexToRgb(hex);
  const [r2, g2, b2] = hexToRgb(withHex);
  return rgbToHex(r1 + (r2 - r1) * amount, g1 + (g2 - g1) * amount, b1 + (b2 - b1) * amount);
}
function gradTop(hex: string): string { return mix(hex, WARM, 0.32); }
function gradBase(hex: string): string { return mix(hex, WARM, 0.08); }
function gradId(hex: string): string { return `sbc-grad-${hex.replace('#', '')}`; }
function fillFor(color: string): string { return isHex(color) ? `url(#${gradId(color)})` : color; }
function easeOutCubic(t: number): number { return 1 - Math.pow(1 - t, 3); }

/** Retângulo com cantos superiores arredondados e base reta. */
function topRoundedRectPath(x: number, y: number, w: number, h: number, r: number): string {
  const rr = Math.max(0, Math.min(r, w / 2, h));
  return [
    `M ${x} ${y + h}`,
    `L ${x} ${y + rr}`,
    `Q ${x} ${y} ${x + rr} ${y}`,
    `L ${x + w - rr} ${y}`,
    `Q ${x + w} ${y} ${x + w} ${y + rr}`,
    `L ${x + w} ${y + h}`,
    'Z',
  ].join(' ');
}

/** Peso de largura de cada bucket: mês atual (destaque) ganha mais espaço; a
 * barra de comparação, menos. Os demais têm peso 1. */
function slotWeight(b: OverviewBucket): number {
  if (b.emphasis) return 1.5;
  if (b.comparison) return 0.72;
  return 1;
}

/** Largura máxima da barra por bucket, acompanhando o peso do slot. */
function maxBarWidth(b: OverviewBucket): number {
  if (b.emphasis) return 52;
  if (b.comparison) return 26;
  return 42;
}

/** Geometria-alvo (grow=1) de todo o gráfico. As cores dos segmentos já saem
 * remapeadas para a paleta ativa. */
function buildModel(
  buckets: OverviewBucket[], metric: Metric, width: number, height: number,
  noScroll: boolean, paletteId: string, goal: number | undefined, showEffort: boolean,
  effortFlat: number | undefined, currentGoal: number | undefined,
): Model {
  const weights = buckets.map(slotWeight);
  const totalWeight = weights.reduce((s, w) => s + w, 0) || 1;
  const naturalUnit = (width - PAD_LEFT) / totalWeight;
  const unit = noScroll ? naturalUnit : Math.max(naturalUnit, MIN_SLOT);
  const chartW = noScroll ? width : PAD_LEFT + unit * totalWeight;
  const innerH = height - PAD_TOP - PAD_BOTTOM;
  const baseY = PAD_TOP + innerH;
  // O eixo precisa absorver a meta e a série de esforço: uma meta acima da barra
  // mais alta seria cortada silenciosamente fora do plot.
  const axisUnit = AXIS_UNIT[metric];
  const rawMax = Math.max(
    ...buckets.map((b) => Math.max(b.total, showEffort ? b.effectiveS ?? 0 : 0)),
    goal ?? 0,
    effortFlat ?? 0,
    axisUnit, // piso: sem dados, um eixo de 0–1h/1km é mais legível que um de 0–1s/1m
  );
  // Topo redondo e acima do máximo: dá folga sobre a barra mais alta e faz as 5
  // linhas da grade caírem em valores legíveis.
  const maxV = niceAxisMax(rawMax, {
    unit: axisUnit, ticks: GRID_TICKS, integer: INTEGER_METRICS.has(metric),
  });

  let cursor = PAD_LEFT;
  const layout: SlotLayout[] = buckets.map((b, i) => {
    const slot = unit * weights[i];
    const x0 = cursor;
    cursor += slot;
    return { x0, slot, center: x0 + slot / 2 };
  });

  const grid = Array.from({ length: GRID_TICKS + 1 }, (_, i) => i / GRID_TICKS).map((f) => ({
    y: baseY - f * innerH, label: fmtAxis(maxV * f, metric), base: f === 0,
  }));

  const bars: Bar[] = buckets.map((b, i) => {
    const { slot, center } = layout[i];
    const barW = Math.min(slot * 0.62, maxBarWidth(b));
    const x = center - barW / 2;
    const opacity = b.comparison ? 0.4 : 1;
    const topIdx = b.segments.length - 1;
    let acc = 0;
    const segs: Seg[] = b.segments.map((s, si) => {
      const h = (s.value / maxV) * innerH;
      acc += h;
      const y = baseY - acc;
      return { x, y, w: barW, h, color: remapChartColor(s.color, paletteId), label: s.label, value: s.value, opacity, top: si === topIdx };
    });
    // Barras de comparação ficam fora da série de esforço (não são cronológicas).
    const effS = b.effectiveS ?? 0;
    const effY = showEffort && !b.comparison && b.effectiveS !== undefined
      ? baseY - (effS / maxV) * innerH
      : null;
    return {
      key: b.key, label: b.label, center, barW, x, comparison: !!b.comparison,
      total: b.total, topY: baseY - acc, segs, effY, effS,
    };
  });

  const goalY = goal && goal > 0 ? baseY - (goal / maxV) * innerH : null;
  const effortFlatY = effortFlat && effortFlat > 0 ? baseY - (effortFlat / maxV) * innerH : null;

  // Meta: reta quando o período está fechado; com degrau sobre o bucket em curso.
  // Saltos (M) em vez de conectores verticais — degrau legível sem poluir.
  let goalPath = '';
  if (goalY !== null && goal) {
    const right = chartW;
    // O bucket em curso é o último NÃO-comparação ("12 meses" põe a comparação depois dele).
    let idx = -1;
    for (let i = buckets.length - 1; i >= 0; i--) if (!buckets[i].comparison) { idx = i; break; }
    if (currentGoal === undefined || currentGoal >= goal || idx < 0) {
      goalPath = `M ${PAD_LEFT} ${goalY} L ${right} ${goalY}`;
    } else {
      const { x0, slot } = layout[idx];
      const stepStart = Math.max(PAD_LEFT, x0);
      const stepEnd = Math.min(right, x0 + slot);
      const yCur = baseY - (currentGoal / maxV) * innerH;
      const parts = [`M ${PAD_LEFT} ${goalY} L ${stepStart} ${goalY}`, `M ${stepStart} ${yCur} L ${stepEnd} ${yCur}`];
      if (stepEnd < right) parts.push(`M ${stepEnd} ${goalY} L ${right} ${goalY}`);
      goalPath = parts.join(' ');
    }
  }

  return { chartW, baseY, layout, grid, bars, goalPath, goalY, effortFlatY };
}

/** Interpola um bar do estado anterior (mesma key) até o alvo. Séries removidas
 * encolhem a 0 no lugar; novas crescem de 0; a pilha é re-empilhada por quadro. */
function interpBar(from: Bar | undefined, to: Bar, e: number, baseY: number): Bar {
  const fromSegs = from?.segs ?? [];
  const fromByLabel = new Map(fromSegs.map((s) => [s.label, s]));
  const toByLabel = new Map(to.segs.map((s) => [s.label, s]));
  // Ordem = a do alvo; séries removidas voltam à sua posição anterior.
  const order: string[] = to.segs.map((s) => s.label);
  fromSegs.forEach((s, idx) => {
    if (!toByLabel.has(s.label)) order.splice(Math.min(idx, order.length), 0, s.label);
  });

  const rows = order.map((label) => {
    const fs = fromByLabel.get(label);
    const ts = toByLabel.get(label);
    const fromH = fs?.h ?? 0;
    const toH = ts?.h ?? 0;
    return { label, h: fromH + (toH - fromH) * e, color: ts?.color ?? fs?.color ?? '#5C534A', value: ts?.value ?? 0 };
  });

  let topIdx = -1;
  for (let i = rows.length - 1; i >= 0; i--) if (rows[i].h > 0.5) { topIdx = i; break; }

  let acc = 0;
  const opacity = to.comparison ? 0.4 : 1;
  const segs: Seg[] = rows.map((r, i) => {
    acc += r.h;
    const y = baseY - acc;
    return { x: to.x, y, w: to.barW, h: r.h, color: r.color, label: r.label, value: r.value, opacity, top: i === topIdx };
  });
  // O ponto de esforço anima junto com as barras; um bucket novo cresce da base.
  const fromEffY = from?.effY ?? baseY;
  const effY = to.effY === null ? null : fromEffY + (to.effY - fromEffY) * e;
  return {
    key: to.key, label: to.label, center: to.center, barW: to.barW, x: to.x,
    comparison: to.comparison, total: to.total, topY: baseY - acc, segs, effY, effS: to.effS,
  };
}

// Dimensões do tooltip.
const TT_PAD = 8;
const TT_ROW = 15;
const TT_DOT = 7;
const TT_FS = 10;

/** Barras empilhadas por tipo de atividade. Portado do gráfico do web. */
export function StackedBarChart({
  buckets, metric, width, height = 200, noScroll = false, animationKey,
  goal, goalLabel = 'Meta', goalUnit = '', currentGoal, showEffort = false, effortFlat, effortFlatLabel = 'Média',
  effortFlatColor = colors.ink2, effortColor = colors.ink2,
}: Props) {
  const [display, setDisplay] = useState<Bar[]>([]);
  const [selected, setSelected] = useState<number | null>(null);
  const [reduceMotion, setReduceMotion] = useState(false);

  const displayRef = useRef<Bar[]>([]);
  const rafRef = useRef<number | undefined>(undefined);

  const paletteId = useChartPaletteStore((s) => s.paletteId);
  const model = useMemo(
    () => buildModel(buckets, metric, width, height, noScroll, paletteId, goal, showEffort, effortFlat, currentGoal),
    [buckets, metric, width, height, noScroll, paletteId, goal, showEffort, effortFlat, currentGoal],
  );

  useEffect(() => {
    let mounted = true;
    AccessibilityInfo.isReduceMotionEnabled().then((v) => { if (mounted) setReduceMotion(v); });
    const sub = AccessibilityInfo.addEventListener('reduceMotionChanged', (v) => setReduceMotion(v));
    return () => { mounted = false; sub.remove(); };
  }, []);

  // Fecha o tooltip ao trocar período/métrica (não na legenda).
  useEffect(() => { setSelected(null); }, [animationKey]);

  const setDisp = (bars: Bar[]) => { displayRef.current = bars; setDisplay(bars); };

  // Tween: interpola do estado atual até o alvo a cada mudança dos dados.
  useEffect(() => {
    const target = model.bars;
    const baseY = model.baseY;
    if (rafRef.current != null) cancelAnimationFrame(rafRef.current);
    if (reduceMotion) { setDisp(target); return; }
    const fromByKey = new Map(displayRef.current.map((b) => [b.key, b]));
    const start = Date.now();
    const step = () => {
      const t = Math.min(1, (Date.now() - start) / ANIM_MS);
      if (t >= 1) { setDisp(target); rafRef.current = undefined; return; }
      const e = easeOutCubic(t);
      setDisp(target.map((tb) => interpBar(fromByKey.get(tb.key), tb, e, baseY)));
      rafRef.current = requestAnimationFrame(step);
    };
    rafRef.current = requestAnimationFrame(step);
    return () => { if (rafRef.current != null) cancelAnimationFrame(rafRef.current); };
  }, [model, reduceMotion]);

  if (buckets.length === 0 || width <= 0) return null;

  const { chartW, baseY, layout, grid, goalPath, goalY, effortFlatY } = model;

  // Curva do esforço ponderado: cúbica monotônica (suaviza sem inventar picos).
  // Quebra (null) nos buckets sem ponto.
  const effortPath = smoothLinePath(
    display.map<LinePoint | null>((b) => (b.effY === null ? null : { x: b.center, y: b.effY })),
  );

  // Cores distintas atualmente renderizadas (inclui séries que estão encolhendo).
  const gradColors = Array.from(
    new Set(display.flatMap((b) => b.segs.map((s) => s.color)).filter(isHex)),
  );

  // ---- Tooltip (opcional) ----
  let tooltip: React.ReactNode = null;
  const selBucket = selected != null ? buckets[selected] : null;
  if (selected != null && selBucket && selBucket.segments.length > 0 && layout[selected]) {
    const b = selBucket;
    const { center } = layout[selected];
    const barTopY = display[selected]?.topY ?? model.bars[selected]?.topY ?? baseY;
    const showTotal = b.segments.length > 1;
    const effortLabel = showEffort && b.effectiveS !== undefined
      ? `Esforço  ${fmtValue(b.effectiveS, metric)}`
      : null;
    const lineCount = 1 + b.segments.length + (showTotal ? 1 : 0) + (effortLabel ? 1 : 0);
    const boxH = TT_PAD * 2 + lineCount * TT_ROW;

    const rowStrings = b.segments.map((s) => `${s.label}  ${fmtValue(s.value, metric)}`);
    if (showTotal) rowStrings.push(`Total  ${fmtValue(b.total, metric)}`);
    if (effortLabel) rowStrings.push(effortLabel);
    const maxLen = Math.max(b.label.length, ...rowStrings.map((r) => r.length));
    const boxW = Math.min(Math.max(104, maxLen * 5.9 + TT_DOT + 22), chartW - 8);

    let by = barTopY - boxH - 6;
    if (by < 2) by = Math.min(barTopY + 6, height - boxH - 2);
    if (by < 2) by = 2;
    const bx = Math.min(Math.max(center - boxW / 2, 4), chartW - boxW - 4);

    const textX = bx + TT_PAD + TT_DOT + 6;
    const valX = bx + boxW - TT_PAD;
    // Linha do esforço ponderado, logo abaixo do total.
    const effortY = by + TT_PAD + TT_FS + TT_ROW * (b.segments.length + 1 + (showTotal ? 1 : 0));

    tooltip = (
      <React.Fragment>
        <Rect
          x={bx}
          y={by}
          width={boxW}
          height={boxH}
          rx={8}
          fill={colors.surface}
          stroke={colors.line}
          strokeWidth={1}
          onPress={() => setSelected(null)}
        />
        <SvgText x={bx + TT_PAD} y={by + TT_PAD + TT_FS} fontSize={TT_FS} fontWeight="700" fill={colors.ink}>
          {b.label}
        </SvgText>
        {b.segments.map((s, k) => {
          const lineY = by + TT_PAD + TT_FS + TT_ROW * (k + 1);
          return (
            <React.Fragment key={`tt-${k}`}>
              <Rect x={bx + TT_PAD} y={lineY - TT_DOT + 0.5} width={TT_DOT} height={TT_DOT} rx={2} fill={remapChartColor(s.color, paletteId)} />
              <SvgText x={textX} y={lineY} fontSize={TT_FS} fill={colors.ink2}>
                {s.label}
              </SvgText>
              <SvgText x={valX} y={lineY} fontSize={TT_FS} fill={colors.ink} textAnchor="end" fontFamily="GeistMono">
                {fmtValue(s.value, metric)}
              </SvgText>
            </React.Fragment>
          );
        })}
        {showTotal && (
          <React.Fragment>
            <SvgText
              x={textX}
              y={by + TT_PAD + TT_FS + TT_ROW * (b.segments.length + 1)}
              fontSize={TT_FS}
              fill={colors.ink3}
              fontWeight="700"
            >
              Total
            </SvgText>
            <SvgText
              x={valX}
              y={by + TT_PAD + TT_FS + TT_ROW * (b.segments.length + 1)}
              fontSize={TT_FS}
              fill={colors.ink}
              textAnchor="end"
              fontWeight="700"
              fontFamily="GeistMono"
            >
              {fmtValue(b.total, metric)}
            </SvgText>
          </React.Fragment>
        )}
        {effortLabel && (
          <React.Fragment>
            <Line
              x1={bx + TT_PAD}
              y1={effortY - TT_FS / 2}
              x2={bx + TT_PAD + TT_DOT}
              y2={effortY - TT_FS / 2}
              stroke={colors.ink}
              strokeWidth={2}
            />
            <SvgText x={textX} y={effortY} fontSize={TT_FS} fill={colors.ink2}>
              Esforço
            </SvgText>
            <SvgText x={valX} y={effortY} fontSize={TT_FS} fill={colors.ink} textAnchor="end" fontFamily="GeistMono">
              {fmtValue(b.effectiveS ?? 0, metric)}
            </SvgText>
          </React.Fragment>
        )}
      </React.Fragment>
    );
  }

  const svg = (
    <Svg width={chartW} height={height}>
      <Defs>
        {gradColors.map((c) => (
          <LinearGradient key={gradId(c)} id={gradId(c)} x1="0" y1="0" x2="0" y2="1">
            <Stop offset="0" stopColor={gradTop(c)} />
            <Stop offset="1" stopColor={gradBase(c)} />
          </LinearGradient>
        ))}
        {/* Painel da área de plot: um só tom com rampa de opacidade (o degradê some
            na base, onde a linha de eixo assume). Segue o tema pelo proxy `colors`. */}
        <LinearGradient id="sbc-plot-bg" x1="0" y1="0" x2="0" y2="1">
          <Stop offset="0" stopColor={colors.surfaceMute} stopOpacity={0.7} />
          <Stop offset="1" stopColor={colors.surfaceMute} stopOpacity={0.15} />
        </LinearGradient>
      </Defs>

      {/* Largura em `chartW` (não na da tela): no scroll horizontal o painel acompanha as barras. */}
      <Rect x={PAD_LEFT} y={PAD_TOP} width={chartW - PAD_LEFT} height={baseY - PAD_TOP} fill="url(#sbc-plot-bg)" />

      {grid.map((g, i) => (
        <React.Fragment key={`g${i}`}>
          <Line
            x1={PAD_LEFT} y1={g.y} x2={chartW} y2={g.y}
            stroke={g.base ? colors.lineDeep : colors.line}
            strokeWidth={g.base ? 1 : 0.5}
            strokeOpacity={g.base ? 0.8 : 0.4}
          />
          <SvgText x={PAD_LEFT - 6} y={g.y + 3} fontSize={9} fill={colors.ink3} textAnchor="end">
            {g.label}
          </SvgText>
        </React.Fragment>
      ))}

      {display.map((b) => (
        <React.Fragment key={b.key}>
          {b.segs.map((s, si) => {
            const fill = fillFor(s.color);
            if (s.top && s.h > 0.5) {
              const r = Math.min(TOP_RADIUS, s.w / 2, s.h);
              return (
                <Path key={`${b.key}-${si}`} d={topRoundedRectPath(s.x, s.y, s.w, s.h, r)} fill={fill} fillOpacity={s.opacity} />
              );
            }
            return (
              <Rect key={`${b.key}-${si}`} x={s.x} y={s.y} width={s.w} height={Math.max(0, s.h)} fill={fill} fillOpacity={s.opacity} rx={0} />
            );
          })}
        </React.Fragment>
      ))}

      {model.bars.map((b) => (
        <SvgText
          key={`lbl-${b.key}`}
          x={b.center}
          y={height - 6}
          fontSize={9}
          fill={b.comparison ? colors.ink4 : colors.ink3}
          textAnchor="middle"
        >
          {b.label}
        </SvgText>
      ))}

      {/* Linhas de referência: pintam por cima das barras, abaixo dos toques.

          Cada uma vai duas vezes: um traço largo em `colors.surface` (o halo) e a cor
          por cima. Desde que o esforço passou a ser ancorado no vigoroso, a linha corre
          DENTRO das barras em vez de acima delas, então ela é lida contra 48 cores de
          preenchimento (8 papéis × 6 paletas). Sem o halo nenhuma cor passa de 8% de
          cobertura; com ele, os valores de `reference-lines.ts` cobrem 100%. Pela mesma
          razão não há strokeOpacity nas cores: opacidade mistura a linha com a barra
          por baixo, que é o que destrói o contraste. O halo lê `colors` (proxy do tema),
          então acompanha claro/escuro sozinho. */}
      {goalY != null && (
        <React.Fragment>
          <Path d={goalPath} fill="none" stroke={colors.surface} strokeWidth={3.5} strokeOpacity={0.9} strokeLinecap="round" />
          <Path
            d={goalPath}
            fill="none"
            stroke={colors.ink3}
            strokeWidth={1.25}
            strokeDasharray="3 3"
          />
          <SvgText x={chartW - 4} y={goalY - 5} fontSize={8.5} fill={colors.ink3} fillOpacity={0.85} textAnchor="end" fontFamily="GeistMono">
            {`${goalLabel} · ${fmtCompact(goal ?? 0, metric)}${goalUnit}`}
          </SvgText>
        </React.Fragment>
      )}

      {effortFlatY != null && (
        <React.Fragment>
          {/* Pontilhada: traço diferente da meta tracejada e da polilinha sólida.
              Rótulo à esquerda; a meta ancora à direita, então nunca colidem. */}
          <Line
            x1={PAD_LEFT} y1={effortFlatY} x2={chartW} y2={effortFlatY}
            stroke={colors.surface} strokeWidth={3.5} strokeOpacity={0.9} strokeLinecap="round"
          />
          <Line
            x1={PAD_LEFT}
            y1={effortFlatY}
            x2={chartW}
            y2={effortFlatY}
            stroke={effortFlatColor}
            strokeWidth={1.5}
            strokeDasharray="1 3"
            strokeLinecap="round"
          />
          <SvgText x={PAD_LEFT + 4} y={effortFlatY - 5} fontSize={8.5} fill={effortFlatColor} fontFamily="GeistMono">
            {`${effortFlatLabel} · ${fmtCompact(effortFlat ?? 0, metric)}`}
          </SvgText>
        </React.Fragment>
      )}

      {effortPath !== '' && (
        <React.Fragment>
          <Path d={effortPath} fill="none" stroke={colors.surface} strokeWidth={4.5} strokeOpacity={0.9} strokeLinecap="round" strokeLinejoin="round" />
          <Path d={effortPath} fill="none" stroke={effortColor} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
          {display.map((b) => (b.effY === null ? null : (
            <React.Fragment key={`eff-${b.key}`}>
              <Circle cx={b.center} cy={b.effY} r={3.2} fill={colors.surface} fillOpacity={0.9} />
              <Circle cx={b.center} cy={b.effY} r={2.2} fill={effortColor} />
            </React.Fragment>
          )))}
        </React.Fragment>
      )}

      {/* Áreas transparentes de toque, por slot (renderizadas por cima das barras). */}
      {layout.map((l, i) => (
        <Rect
          key={`tap-${i}`}
          x={l.x0}
          y={0}
          width={l.slot}
          height={height}
          fill="transparent"
          onPress={() => setSelected((prev) => (prev === i ? null : i))}
        />
      ))}

      {tooltip}
    </Svg>
  );

  if (chartW > width) {
    return (
      <ScrollView horizontal showsHorizontalScrollIndicator={false}>
        {svg}
      </ScrollView>
    );
  }
  return svg;
}

// web/src/app/features/workout-history/components/stacked-bar-chart.component.ts
import { ChangeDetectionStrategy, Component, DestroyRef, computed, effect, inject, input, signal } from '@angular/core';
import { smoothLinePath, niceAxisMax, compactNumber, type LinePoint } from '@vitale/shared';
import type { Metric, OverviewBucket } from '../data/overview';
import { ChartPaletteService } from '@core/services/chart-palette.service';

interface Seg {
  x: number; y: number; w: number; h: number;
  color: string; fill: string; label: string; value: number; opacity: number;
  top: boolean; d: string;
}
interface Bar {
  key: string; label: string; cx: number; segs: Seg[]; topY: number; total: number; faded: boolean;
  /** Y do ponto de esforço ponderado; `null` = bucket sem ponto (comparação / série desligada). */
  effY: number | null;
  /** Valor do esforço em segundos, para o tooltip. */
  effS: number;
  /** Limites do slot do bucket — usados para o degrau da meta no bucket em curso. */
  x0: number;
  slotW: number;
}
/** `base` = linha do zero: fecha o painel do plot, então tem traço mais firme. */
interface GridLine { y: number; label: string; base: boolean; }

// Tom quente para suavizar/clarear as cores das séries (casa com a paleta bege/creme).
const WARM = '#FBF1E2';
const TOP_RADIUS = 6;
const ANIM_MS = 360;

/** Divisões do eixo Y: 4 passos = 5 linhas de grade (com a do zero). */
const GRID_TICKS = 4;
/** Unidade em que cada métrica é lida — o eixo escolhe passos redondos nela. */
const AXIS_UNIT: Record<Metric, number> = { distance: 1000, duration: 3600, calories: 1, count: 1 };
/** Métricas sem casa decimal: o passo do eixo tem que ser inteiro. */
const INTEGER_METRICS: ReadonlySet<Metric> = new Set<Metric>(['calories', 'count']);

const HEX_RE = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;
function isHex(c: string): boolean { return HEX_RE.test(c); }
function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  const full = h.length === 3 ? h.split('').map((c) => c + c).join('') : h;
  const n = parseInt(full, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}
function rgbToHex(r: number, g: number, b: number): string {
  const to = (v: number) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0');
  return `#${to(r)}${to(g)}${to(b)}`;
}
function mix(hex: string, withHex: string, amount: number): string {
  const [r1, g1, b1] = hexToRgb(hex);
  const [r2, g2, b2] = hexToRgb(withHex);
  return rgbToHex(r1 + (r2 - r1) * amount, g1 + (g2 - g1) * amount, b1 + (b2 - b1) * amount);
}
function easeOutCubic(t: number): number { return 1 - Math.pow(1 - t, 3); }

/** Retângulo com cantos superiores arredondados e base reta. */
function topRoundedRectPath(x: number, y: number, w: number, h: number, r: number): string {
  const rr = Math.max(0, Math.min(r, w / 2, h));
  return [
    `M ${x} ${y + h}`,
    `L ${x} ${y + rr}`,
    `Q ${x} ${y} ${x + rr} ${y}`,
    `L ${x + w - rr} ${y}`,
    `Q ${x + w} ${y} ${x + w} ${y + rr}`,
    `L ${x + w} ${y + h}`,
    'Z',
  ].join(' ');
}

@Component({
  selector: 'rt-stacked-bar-chart',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './stacked-bar-chart.component.html',
  styleUrl: './stacked-bar-chart.component.scss',
})
export class StackedBarChartComponent {
  readonly buckets = input.required<OverviewBucket[]>();
  readonly metric = input.required<Metric>();
  /** Meta de referência (mesma unidade das barras); `undefined` = sem linha. */
  readonly goal = input<number | undefined>(undefined);
  /** Rótulo da linha de meta (ex.: "OMS"). */
  readonly goalLabel = input('Meta');
  /** Sufixo de unidade do rótulo ("/mês"): sem ele "14h" é lido como total do período. */
  readonly goalUnit = input('');
  /**
   * Meta do bucket em curso, proporcional ao tempo decorrido. Quando presente, a
   * linha da meta desce em degrau sobre esse bucket — comparar um mês pela metade
   * com a meta cheia faria a última barra parecer sempre um fracasso.
   */
  readonly currentGoal = input<number | undefined>(undefined);
  /** Desenha a polilinha de esforço ponderado a partir de `bucket.effectiveS`. */
  readonly showEffort = input(false);
  /**
   * Reta horizontal com o esforço médio por bucket. Combina com `showEffort`: a
   * polilinha mostra a variação, a reta mostra o patamar médio para comparar direto
   * com a meta. No período "Semana" aparece sozinha (lá não há progressão).
   */
  readonly effortFlat = input<number | undefined>(undefined);
  /** Rótulo da reta de média. */
  readonly effortFlatLabel = input('Média');
  /** Cor da reta de média (esquema configurável em Preferências). */
  readonly effortFlatColor = input('var(--ink-2)');
  /** Cor da polilinha de progressão. */
  readonly effortColor = input('var(--ink-2)');
  private readonly palette = inject(ChartPaletteService);

  protected readonly w = 600;
  protected readonly h = 240;
  protected readonly padL = 40;
  protected readonly padR = 14;
  protected readonly padT = 18;
  protected readonly padB = 28;

  // O eixo precisa absorver a meta e a série de esforço: uma meta acima da barra
  // mais alta seria cortada silenciosamente fora do plot.
  private readonly max = computed(() => {
    const eff = this.showEffort();
    const m = this.metric();
    const unit = AXIS_UNIT[m];
    const raw = Math.max(
      unit, // piso: sem dados, um eixo de 0–1h/1km é mais legível que um de 0–1s/1m
      this.goal() ?? 0,
      this.effortFlat() ?? 0,
      ...this.buckets().map((b) => Math.max(b.total, eff ? b.effectiveS ?? 0 : 0)),
    );
    // Topo redondo e acima do máximo: dá folga sobre a barra mais alta e faz as 5
    // linhas da grade caírem em valores legíveis.
    return niceAxisMax(raw, { unit, ticks: GRID_TICKS, integer: INTEGER_METRICS.has(m) });
  });

  // `bars()` = estado-alvo (geometria final). `display()` = o que é renderizado,
  // interpolado quadro-a-quadro do estado atual até o alvo (troca de período,
  // métrica ou remoção de série na legenda).
  private readonly display = signal<Bar[]>([]);
  protected readonly displayBars = this.display.asReadonly();
  private current: Bar[] = [];
  private raf = 0;
  private readonly reduceMotion =
    typeof window !== 'undefined' && !!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;

  constructor() {
    // Dispara o tween sempre que o alvo muda. O `.set` acontece fora da execução
    // reativa (via microtask/rAF) para não escrever signal dentro do effect.
    effect(() => {
      const target = this.bars();
      queueMicrotask(() => this.animateTo(target));
    });
    inject(DestroyRef).onDestroy(() => cancelAnimationFrame(this.raf));
  }

  private setDisplay(bars: Bar[]): void {
    this.current = bars;
    this.display.set(bars);
  }

  private animateTo(target: Bar[]): void {
    cancelAnimationFrame(this.raf);
    if (this.reduceMotion || typeof requestAnimationFrame === 'undefined') {
      this.setDisplay(target);
      return;
    }
    const fromByKey = new Map(this.current.map((b) => [b.key, b]));
    const start = performance.now();
    const step = (now: number) => {
      const t = Math.min(1, (now - start) / ANIM_MS);
      if (t >= 1) {
        this.setDisplay(target); // assenta exatamente no alvo (ordem/arredondado corretos)
        return;
      }
      const e = easeOutCubic(t);
      this.setDisplay(target.map((tb) => this.interpBar(fromByKey.get(tb.key), tb, e)));
      this.raf = requestAnimationFrame(step);
    };
    this.raf = requestAnimationFrame(step);
  }

  /** Interpola um bar entre o estado anterior (mesma key) e o alvo.
   * Séries removidas encolhem a 0; novas crescem de 0; a pilha é re-empilhada por quadro. */
  private interpBar(from: Bar | undefined, to: Bar, e: number): Bar {
    const fromSegs = from?.segs ?? [];
    const fromByLabel = new Map(fromSegs.map((s) => [s.label, s]));
    const toByLabel = new Map(to.segs.map((s) => [s.label, s]));
    // Ordem = a do alvo; séries removidas voltam à sua posição anterior (encolhem no lugar).
    const order: string[] = to.segs.map((s) => s.label);
    fromSegs.forEach((s, idx) => {
      if (!toByLabel.has(s.label)) order.splice(Math.min(idx, order.length), 0, s.label);
    });

    const barW = to.segs[0]?.w ?? fromSegs[0]?.w ?? 0;
    const barX = to.segs[0]?.x ?? fromSegs[0]?.x ?? 0;
    const baseY = this.h - this.padB;

    const rows = order.map((label) => {
      const fs = fromByLabel.get(label);
      const ts = toByLabel.get(label);
      const fromH = fs?.h ?? 0;
      const toH = ts?.h ?? 0;
      return {
        label,
        h: fromH + (toH - fromH) * e,
        color: ts?.color ?? fs?.color ?? 'var(--ink-3)',
        value: ts?.value ?? 0,
      };
    });

    let topIdx = -1;
    for (let i = rows.length - 1; i >= 0; i--) if (rows[i].h > 0.5) { topIdx = i; break; }

    let acc = 0;
    const opacity = to.faded ? 0.4 : 1;
    const segs: Seg[] = rows.map((r, i) => {
      acc += r.h;
      const y = baseY - acc;
      const top = i === topIdx;
      const rr = Math.min(TOP_RADIUS, barW / 2, r.h);
      return {
        x: barX, y, w: barW, h: r.h, color: r.color, fill: this.fillFor(r.color),
        label: r.label, value: r.value, opacity,
        top, d: top ? topRoundedRectPath(barX, y, barW, r.h, rr) : '',
      };
    });
    // O ponto de esforço anima junto com as barras; um bucket novo cresce da base.
    const effY = to.effY === null ? null : (from?.effY ?? baseY) + (to.effY - (from?.effY ?? baseY)) * e;

    return {
      key: to.key, label: to.label, cx: barX + barW / 2, segs, topY: baseY - acc,
      total: to.total, faded: to.faded, effY, effS: to.effS, x0: to.x0, slotW: to.slotW,
    };
  }

  /** Cores distintas atualmente renderizadas (inclui séries que estão encolhendo). */
  protected readonly gradColors = computed<string[]>(() => {
    const set = new Set<string>();
    for (const b of this.display()) for (const s of b.segs) if (isHex(s.color)) set.add(s.color);
    return [...set];
  });

  protected gradId(color: string): string { return `sbc-grad-${color.replace('#', '')}`; }
  protected topStop(color: string): string { return mix(color, WARM, 0.32); }
  protected baseStop(color: string): string { return mix(color, WARM, 0.08); }
  private fillFor(color: string): string {
    return isHex(color) ? `url(#${this.gradId(color)})` : color;
  }

  /** Peso de largura: mês atual (destaque) ganha mais espaço; comparação, menos. */
  private weightOf(b: OverviewBucket): number {
    if (b.emphasis) return 1.5;
    if (b.comparison) return 0.72;
    return 1;
  }

  /** Largura máxima da barra por bucket, acompanhando o peso do slot. */
  private maxBarWidthOf(b: OverviewBucket): number {
    if (b.emphasis) return 56;
    if (b.comparison) return 30;
    return 42;
  }

  private readonly bars = computed<Bar[]>(() => {
    const bs = this.buckets();
    const max = this.max();
    const plotH = this.h - this.padT - this.padB;
    const plotW = this.w - this.padL - this.padR;

    // Slots com largura proporcional ao peso do bucket (destaque/comparação).
    const weights = bs.map((b) => this.weightOf(b));
    const totalW = weights.reduce((s, x) => s + x, 0) || 1;
    const unit = plotW / totalW;

    let cursor = this.padL;
    return bs.map((b, i) => {
      const slot = unit * weights[i];
      const x0 = cursor;
      cursor += slot;
      const barW = Math.min(slot * 0.62, this.maxBarWidthOf(b));
      const x = x0 + (slot - barW) / 2;
      const opacity = b.comparison ? 0.4 : 1;
      const topIdx = b.segments.length - 1;
      let acc = 0;
      const segs: Seg[] = b.segments.map((s, si) => {
        const segH = (s.value / max) * plotH;
        acc += segH;
        const y = this.h - this.padB - acc;
        const top = si === topIdx;
        const r = Math.min(TOP_RADIUS, barW / 2, segH);
        const color = this.palette.remap(s.color); // reativo à paleta ativa
        return {
          x, y, w: barW, h: segH, color, fill: this.fillFor(color), label: s.label,
          value: s.value, opacity, top, d: top ? topRoundedRectPath(x, y, barW, segH, r) : '',
        };
      });
      const topY = this.h - this.padB - acc;
      // Barras de comparação ficam fora da série de esforço (não são cronológicas).
      const effS = b.effectiveS ?? 0;
      const effY = this.showEffort() && !b.comparison && b.effectiveS !== undefined
        ? this.h - this.padB - (effS / max) * plotH
        : null;
      return {
        key: b.key, label: b.label, cx: x + barW / 2, segs, topY,
        total: b.total, faded: !!b.comparison, effY, effS, x0, slotW: slot,
      };
    });
  });

  protected readonly grid = computed<GridLine[]>(() => {
    const max = this.max();
    const plotH = this.h - this.padT - this.padB;
    return Array.from({ length: GRID_TICKS + 1 }, (_, i) => i / GRID_TICKS).map((f) => ({
      y: this.h - this.padB - f * plotH,
      label: this.fmtShort(max * f),
      base: f === 0,
    }));
  });

  /**
   * Linha da meta. Reta quando o período está todo fechado; com um degrau sobre o
   * bucket em curso quando `currentGoal` chega (mês/semana/ano corrente prorrateado).
   * Emitida como `path` com saltos (`M`) em vez de conectores verticais — o degrau
   * fica legível sem poluir com traços tracejados na vertical.
   */
  protected readonly goalLine = computed<{ d: string; y: number; label: string } | null>(() => {
    const goal = this.goal();
    if (!goal || goal <= 0) return null;
    const plotH = this.h - this.padT - this.padB;
    const max = this.max();
    const yOf = (v: number) => this.h - this.padB - (v / max) * plotH;
    const yFull = yOf(goal);
    const left = this.padL;
    const right = this.w - this.padR;
    const label = `${this.goalLabel()} · ${this.fmtCompact(goal)}${this.goalUnit()}`;

    const cur = this.currentGoal();
    // O bucket em curso é o último NÃO-comparação (em "12 meses" a barra de
    // comparação vem depois dele, fora da ordem cronológica).
    const bars = this.bars();
    let idx = -1;
    for (let i = bars.length - 1; i >= 0; i--) if (!bars[i].faded) { idx = i; break; }

    if (cur === undefined || cur >= goal || idx < 0) {
      return { d: `M ${left} ${yFull} L ${right} ${yFull}`, y: yFull, label };
    }

    const b = bars[idx];
    const stepStart = Math.max(left, b.x0);
    const stepEnd = Math.min(right, b.x0 + b.slotW);
    const yCur = yOf(cur);
    const parts = [`M ${left} ${yFull} L ${stepStart} ${yFull}`, `M ${stepStart} ${yCur} L ${stepEnd} ${yCur}`];
    // Barras depois do bucket em curso (comparação) voltam à meta cheia.
    if (stepEnd < right) parts.push(`M ${stepEnd} ${yFull} L ${right} ${yFull}`);
    return { d: parts.join(' '), y: yFull, label };
  });


  /** Reta horizontal do esforço médio (período "Semana"). */
  protected readonly effortLine = computed<{ y: number; label: string } | null>(() => {
    const v = this.effortFlat();
    if (v === undefined || v <= 0) return null;
    const plotH = this.h - this.padT - this.padB;
    return {
      y: this.h - this.padB - (v / this.max()) * plotH,
      label: `${this.effortFlatLabel()} · ${this.fmtCompact(v)}`,
    };
  });

  /**
   * Curva do esforço ponderado. Cúbica monotônica: suaviza os cantos sem inventar
   * picos entre os buckets. Quebra (`null`) nos buckets sem ponto.
   */
  protected readonly effortPath = computed<string>(() =>
    smoothLinePath(
      this.displayBars().map<LinePoint | null>((b) => (b.effY === null ? null : { x: b.cx, y: b.effY })),
    ),
  );

  protected readonly effortPoints = computed(() =>
    this.displayBars()
      .filter((b) => b.effY !== null)
      .map((b) => ({ key: b.key, cx: b.cx, cy: b.effY as number, value: b.effS })),
  );

  /**
   * Rótulo de valores pequenos: o `fmt()` de duração sempre imprime horas, e a meta
   * diária (~21 min) viraria "0,4h". Abaixo de 1h usa minutos.
   */
  protected fmtCompact(v: number): string {
    if (this.metric() !== 'duration' || v >= 3600) return this.fmt(v);
    return `${this.num(v / 60, 0)} min`;
  }

  /**
   * Rótulo do eixo e do topo da barra: "17.426" kcal vira "17k". O tooltip continua
   * com `fmt()` — lá o valor exato é justamente o que se foi buscar.
   */
  protected fmtShort(v: number): string {
    return INTEGER_METRICS.has(this.metric()) ? compactNumber(v) : this.fmt(v);
  }

  protected fmt(v: number): string {
    switch (this.metric()) {
      case 'distance': return `${this.num(v / 1000, v >= 10000 ? 0 : 1)}km`;
      case 'duration': return `${this.num(v / 3600, v >= 36000 ? 0 : 1)}h`;
      case 'calories': return this.num(Math.round(v), 0);
      case 'count': return this.num(Math.round(v), 0);
    }
  }

  /** Formata com máscara de milhar (pt-BR) e nº fixo de casas decimais. */
  private num(v: number, digits: number): string {
    return v.toLocaleString('pt-BR', {
      minimumFractionDigits: digits,
      maximumFractionDigits: digits,
    });
  }
}

@if (buckets().length) {
  <svg [attr.viewBox]="'0 0 ' + w + ' ' + h" class="chart" preserveAspectRatio="xMidYMid meet">
    <defs>
      @for (c of gradColors(); track c) {
        <linearGradient [attr.id]="gradId(c)" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" [attr.stop-color]="topStop(c)" />
          <stop offset="1" [attr.stop-color]="baseStop(c)" />
        </linearGradient>
      }
      <!-- Painel da área de plot: um só tom com rampa de opacidade (o degradê some
           na base, onde a linha de eixo assume). -->
      <linearGradient id="sbc-plot-bg" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="var(--surface-mute)" stop-opacity="0.7" />
        <stop offset="1" stop-color="var(--surface-mute)" stop-opacity="0.15" />
      </linearGradient>
    </defs>
    <rect [attr.x]="padL" [attr.y]="padT" [attr.width]="w - padL - padR"
      [attr.height]="h - padT - padB" fill="url(#sbc-plot-bg)" />
    @for (g of grid(); track g.y) {
      <line [attr.x1]="padL" [attr.x2]="w - padR" [attr.y1]="g.y" [attr.y2]="g.y"
        [attr.stroke]="g.base ? 'var(--line-deep)' : 'var(--line)'" stroke-width="1"
        [attr.stroke-opacity]="g.base ? 0.8 : 0.45" />
      <text [attr.x]="padL - 6" [attr.y]="g.y + 3" text-anchor="end" font-size="10"
        font-family="Geist Mono, monospace" fill="var(--ink-3)">{{ g.label }}</text>
    }
    @for (b of displayBars(); track b.key) {
      <g>
        @for (s of b.segs; track s.label) {
          @if (s.top && s.h > 0.5) {
            <path [attr.d]="s.d" [attr.fill]="s.fill" [attr.fill-opacity]="s.opacity">
              <title>{{ s.label }} · {{ fmt(s.value) }}</title>
            </path>
          } @else {
            <rect [attr.x]="s.x" [attr.y]="s.y" [attr.width]="s.w" [attr.height]="s.h"
              [attr.fill]="s.fill" [attr.fill-opacity]="s.opacity">
              <title>{{ s.label }} · {{ fmt(s.value) }}</title>
            </rect>
          }
        }
        @if (b.total > 0) {
          <text [attr.x]="b.cx" [attr.y]="b.topY - 5" text-anchor="middle" font-size="10"
            font-family="Geist Mono, monospace" font-weight="600"
            [attr.fill]="'var(--ink)'" [attr.fill-opacity]="b.faded ? 0.55 : 1">{{ fmtShort(b.total) }}</text>
        }
        <text [attr.x]="b.cx" [attr.y]="h - 10" text-anchor="middle" font-size="10"
          [attr.fill]="b.faded ? 'var(--ink-4)' : 'var(--ink-3)'">{{ b.label }}</text>
      </g>
    }
    <!-- Linhas de referência por último: pintam por cima das barras.

         Cada uma vai duas vezes: um traço largo na cor da superfície (o halo) e a cor
         por cima. Desde que o esforço passou a ser ancorado no vigoroso, a linha corre
         DENTRO das barras em vez de acima delas, então ela é lida contra 48 cores de
         preenchimento diferentes (8 papéis × 6 paletas). Sem o halo nenhuma cor passa
         de 8% de cobertura; com ele, os valores de `reference-lines.ts` cobrem 100%.
         Pela mesma razão não há stroke-opacity aqui: opacidade mistura a linha com a
         barra por baixo, que é justamente o que destrói o contraste. -->
    @if (goalLine(); as g) {
      <path [attr.d]="g.d" fill="none" stroke="var(--surface)" stroke-width="3.5"
        stroke-opacity="0.9" stroke-linecap="round" />
      <path [attr.d]="g.d" fill="none" stroke="var(--ink-3)" stroke-width="1.25"
        stroke-dasharray="3 3" />
      <text [attr.x]="w - padR" [attr.y]="g.y - 5" text-anchor="end" font-size="8.5"
        font-family="Geist Mono, monospace" fill="var(--ink-3)" fill-opacity="0.85">{{ g.label }}</text>
    }
    @if (effortLine(); as e) {
      <!-- Pontilhada: traço diferente da meta tracejada e da polilinha sólida. Rótulo
           à esquerda; a meta ancora à direita, então nunca colidem. -->
      <line [attr.x1]="padL" [attr.x2]="w - padR" [attr.y1]="e.y" [attr.y2]="e.y"
        stroke="var(--surface)" stroke-width="3.5" stroke-opacity="0.9" stroke-linecap="round" />
      <line [attr.x1]="padL" [attr.x2]="w - padR" [attr.y1]="e.y" [attr.y2]="e.y"
        [attr.stroke]="effortFlatColor()" stroke-width="1.5"
        stroke-dasharray="1 3" stroke-linecap="round" />
      <text [attr.x]="padL + 4" [attr.y]="e.y - 5" font-size="8.5"
        font-family="Geist Mono, monospace" [attr.fill]="effortFlatColor()">{{ e.label }}</text>
    }
    @if (effortPath()) {
      <path [attr.d]="effortPath()" fill="none" stroke="var(--surface)" stroke-width="4.5"
        stroke-opacity="0.9" stroke-linecap="round" stroke-linejoin="round" />
      <path [attr.d]="effortPath()" fill="none" [attr.stroke]="effortColor()" stroke-width="2"
        stroke-linecap="round" stroke-linejoin="round" />
      @for (p of effortPoints(); track p.key) {
        <circle [attr.cx]="p.cx" [attr.cy]="p.cy" r="3.2" fill="var(--surface)" fill-opacity="0.9" />
        <circle [attr.cx]="p.cx" [attr.cy]="p.cy" r="2.2" [attr.fill]="effortColor()">
          <title>Esforço ponderado · {{ fmtCompact(p.value) }}</title>
        </circle>
      }
    }
  </svg>
} @else {
  <div class="no-data">Sem atividades neste período.</div>
}
